<?php

declare(strict_types=1);

require_once __DIR__ . '/src/db.php';
require_once __DIR__ . '/src/setup.php';
require_once __DIR__ . '/src/import.php';
require_once __DIR__ . '/src/download.php';
require_once __DIR__ . '/src/images.php';
require_once __DIR__ . '/src/storage.php';
require_once __DIR__ . '/src/updater.php';
require_once __DIR__ . '/src/settings.php';
require_once __DIR__ . '/src/i18n.php';
require_once __DIR__ . '/src/icons.php';
require_once __DIR__ . '/src/parts.php';
require_once __DIR__ . '/src/stats.php';

// src/config.php is generated by the setup wizard and deliberately not tracked
// in git (see .gitignore) — a fresh install/update copy never has it yet, so
// this must be an existence check, not an unconditional require, or a bare
// clone would fatal-error instead of redirecting to setup.php.
$configPath = __DIR__ . '/src/config.php';
if (!is_file($configPath)) {
    header('Location: setup.php');
    exit;
}
$config = require $configPath;
if (empty($config['db']['dbname']) || empty($config['db']['user']) || !canConnectToServer()) {
    header('Location: setup.php');
    exit;
}

session_start();

try {
    if (!isInstalled()) {
        installDatabase();
        try {
            $result = downloadAndImportRebrickableData();
            $summaryText = implode(', ', array_map(function ($type, $rows) { return "$type=$rows"; }, array_keys($result['summary']), $result['summary']));
            if (!empty($result['errors'])) {
                $errorsText = implode(', ', array_map(function ($type, $msg) { return "$type: $msg"; }, array_keys($result['errors']), $result['errors']));
                $message = t('setup_completed_message_partial', ['summary' => $summaryText, 'errors' => $errorsText]);
            } else {
                $message = t('setup_completed_message_success', ['summary' => $summaryText]);
            }
        } catch (Throwable $e) {
            $message = t('setup_completed_message_error', ['message' => $e->getMessage()]);
        }
        render(t('setup_completed_title'), '<section class="card"><h2>' . htmlspecialchars(t('setup_completed_heading')) . '</h2><p>' . htmlspecialchars($message) . '</p><p>' . htmlspecialchars(t('setup_completed_reload')) . '</p></section>');
        exit;
    }
} catch (Throwable $e) {
    render(t('setup_error_title'), '<section class="card alert"><h2>' . htmlspecialchars(t('setup_error_heading')) . '</h2><p>' . htmlspecialchars(t('setup_error_message', ['message' => $e->getMessage()])) . '</p></section>');
    exit;
}

require_once __DIR__ . '/src/migrations.php';
if (schemaMigrationPending()) {
    try {
        runAllPendingMigrations();
    } catch (Throwable $e) {
        render(t('setup_error_title'), '<section class="card alert"><h2>' . htmlspecialchars(t('setup_error_heading')) . '</h2><p>' . htmlspecialchars(t('setup_error_message', ['message' => $e->getMessage()])) . '</p></section>');
        exit;
    }
}

$pdo = getPDO();

require_once __DIR__ . '/src/part_translations_sync.php';
if (partTranslationsSyncPending()) {
    try {
        stepPartTranslationsSync();
    } catch (Throwable $e) {
        // Non-fatal: a translation sync hiccup shouldn't take the whole app
        // down. It'll just retry on the next request.
    }
}

function render(string $title, string $content): void
{
    echo '<!DOCTYPE html><html lang="' . htmlspecialchars(getLocale()) . '"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">';
    echo '<title>' . htmlspecialchars($title) . '</title>';
    echo '<link rel="icon" type="image/svg+xml" href="favicon.svg">';
    echo '<link rel="stylesheet" href="style.css">';
    echo '</head><body>';
    echo '<div class="container">';
    echo '<header><div class="brand"><span class="brand-mark">' . file_get_contents(__DIR__ . '/logo.svg') . '</span><div><h1>' . htmlspecialchars(t('app_title')) . '</h1><small>' . htmlspecialchars(t('app_tagline')) . '</small></div></div></header>';
    echo $content;
    echo '<footer>' . htmlspecialchars(t('app_footer', ['year' => date('Y')])) . '</footer>';
    echo '</div></body></html>';
}

function getNavMenu(): array
{
    return [
        ['icon' => 'build', 'labelKey' => 'nav_build', 'href' => $_SERVER['PHP_SELF'], 'children' => []],
        ['icon' => 'sets', 'labelKey' => 'nav_sets', 'href' => '?page=sets', 'children' => [
            ['labelKey' => 'nav_sets_search', 'href' => '?page=sets_search'],
            ['labelKey' => 'nav_minifigs_search', 'href' => '?page=minifigs_search'],
        ]],
        ['icon' => 'bricks', 'labelKey' => 'nav_bricks', 'href' => '?page=bricks', 'children' => [
            ['labelKey' => 'nav_bricks_search', 'href' => '?page=bricks_search'],
            ['labelKey' => 'nav_colors_search', 'href' => '?page=colors_search'],
        ]],
        ['icon' => 'my_sets', 'labelKey' => 'nav_my_sets', 'href' => '?page=my_sets', 'children' => [
            ['labelKey' => 'nav_my_sets_all', 'href' => '?page=my_sets_all'],
            ['labelKey' => 'nav_my_sets_themes', 'href' => '?page=my_sets_themes'],
        ]],
        ['icon' => 'my_bricks', 'labelKey' => 'nav_my_bricks', 'href' => '?page=my_bricks', 'children' => [
            ['labelKey' => 'nav_my_bricks_all', 'href' => '?page=my_bricks_all'],
            ['labelKey' => 'nav_my_bricks_by_location', 'href' => '?page=my_bricks_by_location'],
            ['labelKey' => 'nav_my_bricks_by_type', 'href' => '?page=my_bricks_by_type'],
        ]],
        ['icon' => 'locations', 'labelKey' => 'locations_title', 'href' => '?page=locations', 'children' => [
            ['labelKey' => 'nav_locations_tree', 'href' => '?page=locations'],
        ]],
        ['icon' => 'collection', 'labelKey' => 'nav_my_collection', 'href' => '?page=my_collection', 'children' => []],
    ];
}

function getSearchScopes(): array
{
    return [
        'search' => 'search_scope_all',
        'sets_search' => 'nav_sets',
        'bricks_search' => 'nav_bricks',
        'my_sets_all' => 'nav_my_sets',
        'my_bricks_all' => 'nav_my_bricks',
    ];
}

function renderApp(string $title, string $content, array $user, array $stats): void
{
    $locale = getLocale();
    $currentPage = (string) ($_GET['page'] ?? '');

    echo '<!DOCTYPE html><html lang="' . htmlspecialchars($locale) . '"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">';
    echo '<title>' . htmlspecialchars($title) . '</title>';
    echo '<link rel="icon" type="image/svg+xml" href="favicon.svg">';
    echo '<link rel="stylesheet" href="style.css">';
    echo '</head><body>';

    echo '<div class="status-bar-wrap"><div class="status-bar">';
    echo '<div class="status-stats">';
    echo '<span class="status-stat"><strong>' . number_format($stats['bricks_total']) . '</strong> ' . htmlspecialchars(t('stat_bricks_total')) . '</span>';
    echo '<span class="status-stat"><strong>' . number_format($stats['bricks_distinct']) . '</strong> ' . htmlspecialchars(t('stat_bricks_distinct')) . '</span>';
    echo '<span class="status-stat"><strong>' . number_format($stats['sets']) . '</strong> ' . htmlspecialchars(t('stat_sets')) . '</span>';
    echo '<span class="status-stat"><strong>' . number_format($stats['minifigs']) . '</strong> ' . htmlspecialchars(t('stat_minifigs')) . '</span>';
    echo '</div>';
    echo '<div class="status-user">';
    echo '<a class="status-username" href="?page=settings">' . htmlspecialchars($user['username']) . '</a>';
    echo '<a class="status-icon-link" href="?page=settings" title="' . htmlspecialchars(t('settings_title')) . '">' . getNavIcon('settings') . '</a>';
    echo '<a class="status-icon-link" href="?action=logout" title="' . htmlspecialchars(t('logout')) . '">' . getNavIcon('logout') . '</a>';
    $redirectPage = $currentPage !== '' ? '&page=' . urlencode($currentPage) : '';
    echo '<div class="lang-switcher">';
    echo '<span class="lang-current"><span class="flag-icon">' . getFlagIcon($locale) . '</span></span>';
    echo '<div class="lang-dropdown">';
    foreach (getAvailableLocales() as $flagLocale => $flagLabel) {
        $activeClass = $flagLocale === $locale ? ' active' : '';
        $flagHref = htmlspecialchars('?action=set_locale&locale=' . $flagLocale . $redirectPage);
        echo '<a class="lang-option' . $activeClass . '" href="' . $flagHref . '"><span class="flag-icon">' . getFlagIcon($flagLocale) . '</span>' . htmlspecialchars($flagLabel) . '</a>';
    }
    echo '</div>';
    echo '</div>';
    echo '</div>';
    echo '</div></div>';

    echo '<div class="main-nav-wrap"><header class="main-nav">';
    echo '<a class="logo-link" href="' . htmlspecialchars($_SERVER['PHP_SELF']) . '"><span class="logo-mark">' . file_get_contents(__DIR__ . '/logo.svg') . '</span><span class="logo-text">' . htmlspecialchars(t('app_title')) . '</span></a>';
    echo '<nav class="nav-list">';
    foreach (getNavMenu() as $item) {
        echo '<div class="nav-item">';
        echo '<a class="nav-link" href="' . htmlspecialchars($item['href']) . '"><span class="nav-icon">' . getNavIcon($item['icon']) . '</span><span class="nav-label">' . htmlspecialchars(t($item['labelKey'])) . '</span></a>';
        if (!empty($item['children'])) {
            echo '<div class="nav-dropdown">';
            foreach ($item['children'] as $child) {
                echo '<a href="' . htmlspecialchars($child['href']) . '">' . htmlspecialchars(t($child['labelKey'])) . '</a>';
            }
            echo '</div>';
        }
        echo '</div>';
    }
    echo '</nav>';
    echo '<form class="nav-search" method="get" action="' . htmlspecialchars($_SERVER['PHP_SELF']) . '">';
    echo '<select name="page" aria-label="' . htmlspecialchars(t('search_scope_label')) . '">';
    foreach (getSearchScopes() as $scopeValue => $scopeLabelKey) {
        echo '<option value="' . htmlspecialchars($scopeValue) . '">' . htmlspecialchars(t($scopeLabelKey)) . '</option>';
    }
    echo '</select>';
    echo '<input type="search" name="q" placeholder="' . htmlspecialchars(t('search_placeholder')) . '" aria-label="' . htmlspecialchars(t('search_placeholder')) . '">';
    echo '<button type="submit">' . htmlspecialchars(t('search_button')) . '</button>';
    echo '</form>';
    echo '</header></div>';

    echo '<div class="container">';
    echo '<main>' . $content . '</main>';
    echo '<footer>' . htmlspecialchars(t('app_footer', ['year' => date('Y')])) . '</footer>';
    echo '</div>';
    echo '</body></html>';
}

if (isset($_POST['action']) && $_POST['action'] === 'register') {
    $username = trim($_POST['username'] ?? '');
    $password = $_POST['password'] ?? '';
    $email = trim($_POST['email'] ?? '');

    if ($username !== '' && $password !== '') {
        $hash = password_hash($password, PASSWORD_DEFAULT);
        $stmt = $pdo->prepare('INSERT INTO users (username, password_hash, email) VALUES (?, ?, ?)');
        $stmt->execute([$username, $hash, $email]);
        render(t('register_success_title'), '<section class="card notice"><h2>' . htmlspecialchars(t('register_success_heading')) . '</h2><p>' . htmlspecialchars(t('register_success_message')) . '</p></section>');
        exit;
    }
}

if (isset($_POST['action']) && $_POST['action'] === 'login') {
    $username = trim($_POST['username'] ?? '');
    $password = $_POST['password'] ?? '';
    $stmt = $pdo->prepare('SELECT id, password_hash FROM users WHERE username = ?');
    $stmt->execute([$username]);
    $user = $stmt->fetch();
    if ($user && password_verify($password, $user['password_hash'])) {
        $_SESSION['user_id'] = $user['id'];
        header('Location: ' . $_SERVER['PHP_SELF']);
        exit;
    }
    render(t('login_failed_title'), '<section class="card alert"><h2>' . htmlspecialchars(t('login_failed_heading')) . '</h2><p>' . htmlspecialchars(t('login_failed_message')) . '</p></section>');
    exit;
}

$importMessage = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'import') {
    try {
        $type = $_POST['import_type'] ?? '';
        if (!isset($_FILES['import_file']) || $_FILES['import_file']['error'] !== UPLOAD_ERR_OK) {
            throw new RuntimeException(t('error_import_file_required'));
        }
        $result = importCsv($_FILES['import_file']['tmp_name'], $type);
        $importMessage = t('import_success_rows', ['count' => $result['rows'] ?? 0]);
    } catch (Throwable $e) {
        $importMessage = t('import_failure_message', ['message' => $e->getMessage()]);
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'update_data') {
    try {
        $result = downloadAndImportRebrickableData();
        $summaryText = implode(', ', array_map(function ($type, $rows) { return "$type=$rows"; }, array_keys($result['summary']), $result['summary']));
        if (!empty($result['errors'])) {
            $errorsText = implode(', ', array_map(function ($type, $msg) { return "$type: $msg"; }, array_keys($result['errors']), $result['errors']));
            $importMessage = t('update_partial_message', ['summary' => $summaryText, 'errors' => $errorsText]);
        } else {
            $importMessage = t('update_success_message', ['summary' => $summaryText]);
        }
    } catch (Throwable $e) {
        $importMessage = t('update_failure_message', ['message' => $e->getMessage()]);
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'update_rebrickable_settings') {
    setAppSetting('rebrickable_download_base_url', trim($_POST['download_base_url'] ?? ''));
    setAppSetting('rebrickable_api_url', trim($_POST['api_url'] ?? ''));
    setAppSetting('rebrickable_api_key', trim($_POST['api_key'] ?? ''));
    $importMessage = t('settings_rebrickable_saved');
}

if (isset($_GET['action']) && $_GET['action'] === 'logout') {
    session_destroy();
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
}

if (isset($_GET['action']) && $_GET['action'] === 'set_locale') {
    setSessionLocale((string) ($_GET['locale'] ?? ''));
    $redirectPage = isset($_GET['page']) ? '?page=' . urlencode((string) $_GET['page']) : '';
    header('Location: ' . $_SERVER['PHP_SELF'] . $redirectPage);
    exit;
}

if (!isset($_SESSION['user_id'])) {
    $content = '<section class="card"><h2>' . htmlspecialchars(t('login_title')) . '</h2><form method="post"><input type="hidden" name="action" value="login"><label>' . htmlspecialchars(t('login_username')) . '<input name="username" autocomplete="username"></label><label>' . htmlspecialchars(t('login_password')) . '<input type="password" name="password" autocomplete="current-password"></label><button type="submit">' . htmlspecialchars(t('login_button')) . '</button></form></section>';
    $content .= '<section class="card"><h2>' . htmlspecialchars(t('register_title')) . '</h2><form method="post"><input type="hidden" name="action" value="register"><label>' . htmlspecialchars(t('register_username')) . '<input name="username" autocomplete="username"></label><label>' . htmlspecialchars(t('register_email')) . '<input type="email" name="email" autocomplete="email"></label><label>' . htmlspecialchars(t('register_password')) . '<input type="password" name="password" autocomplete="new-password"></label><button type="submit">' . htmlspecialchars(t('register_button')) . '</button></form></section>';
    render(t('login_register_title'), $content);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'image_tick') {
    header('Content-Type: application/json');
    try {
        $state = $_SESSION['image_download_state'] ?? null;
        if (!is_array($state)) {
            $forceRefresh = ($_POST['force_refresh'] ?? '') === '1';
            $state = initImageDownloadState($forceRefresh);
        }

        $result = stepImageDownload($state);
        $_SESSION['image_download_state'] = $state;

        $payload = buildImageProgressPayload($state, $result['done']);

        if ($result['done']) {
            unset($_SESSION['image_download_state']);
        }

        echo json_encode($payload, JSON_UNESCAPED_UNICODE);
    } catch (Throwable $e) {
        http_response_code(500);
        echo json_encode([
            'status' => 'error',
            'percent' => 0,
            'message' => t('import_error', ['message' => $e->getMessage()]),
            'tables' => [],
        ], JSON_UNESCAPED_UNICODE);
    }
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'check_update') {
    header('Content-Type: application/json');
    try {
        $release = isUpdateAvailable();
        if ($release !== null) {
            $_SESSION['update_available_release'] = $release;
        } else {
            unset($_SESSION['update_available_release']);
        }
        echo json_encode([
            'available' => $release !== null,
            'release' => $release,
            'currentVersion' => getCurrentVersion(),
        ], JSON_UNESCAPED_UNICODE);
    } catch (Throwable $e) {
        http_response_code(500);
        echo json_encode(['available' => false, 'error' => $e->getMessage()], JSON_UNESCAPED_UNICODE);
    }
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'update_tick') {
    header('Content-Type: application/json');
    try {
        $state = $_SESSION['update_state'] ?? null;
        if (!is_array($state)) {
            $release = $_SESSION['update_available_release'] ?? null;
            if ($release === null) {
                throw new RuntimeException(t('update_no_release_selected'));
            }
            $state = initUpdateState($release);
        }

        $result = stepUpdate($state);
        $_SESSION['update_state'] = $state;

        $payload = buildUpdateProgressPayload($state, $result['done']);

        if ($result['done']) {
            unset($_SESSION['update_state'], $_SESSION['update_available_release']);
        }

        echo json_encode($payload, JSON_UNESCAPED_UNICODE);
    } catch (Throwable $e) {
        unset($_SESSION['update_state']);
        http_response_code(500);
        echo json_encode([
            'status' => 'error',
            'percent' => 0,
            'message' => t('update_failed', ['message' => $e->getMessage()]),
        ], JSON_UNESCAPED_UNICODE);
    }
    exit;
}

$locationMessage = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'add_location') {
    $name = trim($_POST['name'] ?? '');
    $type = trim($_POST['type'] ?? '');
    $type = isValidLocationType($type) ? $type : null;
    $parentId = trim($_POST['parent_id'] ?? '') !== '' ? (int) $_POST['parent_id'] : null;
    $childCount = (int) ($_POST['child_count'] ?? 0);
    $namingPattern = trim($_POST['naming_pattern'] ?? '');

    if ($name === '') {
        $locationMessage = t('location_name_required');
    } else {
        try {
            $types = getLocationTypes();
            $supportsBulk = $type !== null && $types[$type]['bulkChildKey'] !== null;
            if ($supportsBulk && $childCount > 0 && $namingPattern !== '') {
                createStorageLocationWithChildren($parentId, $name, $type, $childCount, $namingPattern);
            } else {
                createStorageLocation($parentId, $name, $type);
            }
            $locationMessage = t('location_added_message', ['name' => $name]);
        } catch (Throwable $e) {
            $locationMessage = t('location_save_failed', ['message' => $e->getMessage()]);
        }
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'rename_location') {
    $locationId = (int) ($_POST['location_id'] ?? 0);
    $name = trim($_POST['name'] ?? '');
    $type = trim($_POST['type'] ?? '');
    $type = isValidLocationType($type) ? $type : null;

    if ($name === '') {
        $locationMessage = t('location_name_required');
    } else {
        try {
            renameStorageLocation($locationId, $name, $type);
            $locationMessage = t('location_updated_message');
        } catch (Throwable $e) {
            $locationMessage = t('location_save_failed', ['message' => $e->getMessage()]);
        }
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'delete_location') {
    $locationId = (int) ($_POST['location_id'] ?? 0);
    if (locationHasChildren($locationId)) {
        $locationMessage = t('location_delete_blocked_children');
    } elseif (locationHasStock($locationId)) {
        $locationMessage = t('location_delete_blocked_stock');
    } else {
        try {
            deleteStorageLocation($locationId);
            $locationMessage = t('location_deleted_message');
        } catch (Throwable $e) {
            $locationMessage = t('location_save_failed', ['message' => $e->getMessage()]);
        }
    }
}

if (isset($_GET['action']) && $_GET['action'] === 'location_children') {
    header('Content-Type: application/json');
    $parentId = isset($_GET['parent_id']) && $_GET['parent_id'] !== '' ? (int) $_GET['parent_id'] : null;
    $children = getChildLocations($parentId);
    echo json_encode(['children' => $children], JSON_UNESCAPED_UNICODE);
    exit;
}

if (isset($_GET['action']) && $_GET['action'] === 'part_detail') {
    header('Content-Type: application/json');
    $partId = (int) ($_GET['part_id'] ?? 0);
    $part = getPartDetail($pdo, $partId);
    if ($part === null) {
        http_response_code(404);
        echo json_encode(['error' => t('part_not_found')], JSON_UNESCAPED_UNICODE);
        exit;
    }
    // Best-effort catalog search links built from part_num — we don't import
    // BrickLink/BrickOwl's own external-id mappings (that needs their APIs),
    // so a direct catalog-item link isn't reliably constructible, especially
    // for printed variants whose numbering differs across sites.
    $part['bricklink_url'] = 'https://www.bricklink.com/v2/search.page?q=' . urlencode($part['part_num']);
    $part['brickowl_url'] = 'https://www.brickowl.com/search/catalog?query=' . urlencode($part['part_num']);
    $locale = getLocale();
    $part['translated_name'] = $locale !== 'en' ? getPartTranslation($pdo, $partId, $locale) : null;
    $part['translation_locale'] = $locale;
    $colors = getColorsForPartPicker($pdo, $partId);
    echo json_encode([
        'part' => $part,
        'knownColors' => $colors['known'],
        'otherColors' => $colors['other'],
        'rootLocations' => getChildLocations(null),
        'printParent' => getPrintParent($pdo, $partId),
    ], JSON_UNESCAPED_UNICODE);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'save_part_translation') {
    header('Content-Type: application/json');
    try {
        $partId = (int) ($_POST['part_id'] ?? 0);
        $locale = getLocale();
        $name = trim((string) ($_POST['name'] ?? ''));
        if ($partId <= 0 || $name === '') {
            throw new RuntimeException(t('translation_invalid_input'));
        }
        if ($locale === 'en') {
            throw new RuntimeException(t('translation_locale_is_source'));
        }
        savePartTranslation($pdo, $partId, $locale, $name, (int) $_SESSION['user_id']);
        echo json_encode(['success' => true, 'name' => $name], JSON_UNESCAPED_UNICODE);
    } catch (Throwable $e) {
        http_response_code(400);
        echo json_encode(['success' => false, 'message' => $e->getMessage()], JSON_UNESCAPED_UNICODE);
    }
    exit;
}

if (isset($_GET['action']) && $_GET['action'] === 'part_sets') {
    header('Content-Type: application/json');
    $partId = (int) ($_GET['part_id'] ?? 0);
    echo json_encode(['sets' => getPartSets($pdo, $partId)], JSON_UNESCAPED_UNICODE);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'add_stock') {
    header('Content-Type: application/json');
    try {
        $partId = (int) ($_POST['part_id'] ?? 0);
        $colorId = (int) ($_POST['color_id'] ?? 0);
        $locationId = (int) ($_POST['location_id'] ?? 0);
        $conditionType = ($_POST['condition_type'] ?? '') === 'new' ? 'new' : 'used';
        $quantity = (int) ($_POST['quantity'] ?? 0);

        if ($partId <= 0 || $colorId <= 0 || $locationId <= 0 || $quantity <= 0) {
            throw new RuntimeException(t('add_stock_invalid_input'));
        }
        // A room (or any non-leaf level) alone isn't a valid storage spot —
        // the cascading picker is only meant to bottom out at an actual leaf.
        if (locationHasChildren($locationId)) {
            throw new RuntimeException(t('add_stock_location_not_leaf'));
        }

        $resultingQuantity = addStorageStock($locationId, $partId, $colorId, $conditionType, $quantity, (int) $_SESSION['user_id']);
        refreshAppStatsCache($pdo);

        echo json_encode([
            'success' => true,
            'resultingQuantity' => $resultingQuantity,
            'locationPath' => getStorageLocationPath($locationId),
            'message' => t('add_stock_success', ['quantity' => (string) $quantity, 'total' => (string) $resultingQuantity]),
        ], JSON_UNESCAPED_UNICODE);
    } catch (Throwable $e) {
        http_response_code(400);
        echo json_encode(['success' => false, 'message' => t('add_stock_failed', ['message' => $e->getMessage()])], JSON_UNESCAPED_UNICODE);
    }
    exit;
}

$stmt = $pdo->prepare('SELECT username FROM users WHERE id = ?');
$stmt->execute([$_SESSION['user_id']]);
$user = $stmt->fetch();

if ($user === false) {
    session_destroy();
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
}

if (isset($_GET['page']) && $_GET['page'] === 'settings') {
    $content = '<h1>' . htmlspecialchars(t('settings_title')) . '</h1>';
    $content .= '<p><a href="' . $_SERVER['PHP_SELF'] . '">' . htmlspecialchars(t('settings_back')) . '</a></p>';
    if ($importMessage !== '') {
        $content .= '<p><strong>' . htmlspecialchars($importMessage) . '</strong></p>';
    }
    $content .= '<form method="post"><input type="hidden" name="action" value="update_data"><button type="submit">' . htmlspecialchars(t('settings_update_button')) . '</button></form>';
    $content .= '<p>' . htmlspecialchars(t('settings_update_help')) . '</p>';
    $content .= '<h2>' . htmlspecialchars(t('settings_recent_updates')) . '</h2>';
    $content .= '<ul>';
    $content .= '<li>' . htmlspecialchars(t('settings_last_update_all', ['value' => getAppSetting('last_update_all', t('not_available'))])) . '</li>';
    $content .= '<li>' . htmlspecialchars(t('settings_last_update_parts', ['value' => getAppSetting('last_update_parts', t('not_available'))])) . '</li>';
    $content .= '<li>' . htmlspecialchars(t('settings_last_update_sets', ['value' => getAppSetting('last_update_sets', t('not_available'))])) . '</li>';
    $content .= '<li>' . htmlspecialchars(t('settings_last_update_set_parts', ['value' => getAppSetting('last_update_set_parts', t('not_available'))])) . '</li>';
    $content .= '</ul>';

    $content .= '<h2>' . htmlspecialchars(t('settings_rebrickable_title')) . '</h2>';
    $content .= '<p>' . htmlspecialchars(t('settings_rebrickable_help')) . '</p>';
    $content .= '<form method="post">';
    $content .= '<input type="hidden" name="action" value="update_rebrickable_settings">';
    $content .= '<label>' . htmlspecialchars(t('settings_download_base_url_label'))
        . '<input name="download_base_url" value="' . htmlspecialchars((string) getAppSetting('rebrickable_download_base_url', '')) . '" placeholder="https://cdn.rebrickable.com/media/downloads/"></label>';
    $content .= '<small>' . htmlspecialchars(t('settings_download_base_url_help')) . '</small>';
    $content .= '<label>' . htmlspecialchars(t('settings_api_url_label'))
        . '<input name="api_url" value="' . htmlspecialchars((string) getAppSetting('rebrickable_api_url', '')) . '" placeholder="https://rebrickable.com/api/v3/"></label>';
    $content .= '<small>' . htmlspecialchars(t('settings_api_url_help')) . '</small>';
    $content .= '<label>' . htmlspecialchars(t('settings_api_key_label'))
        . '<input name="api_key" value="' . htmlspecialchars((string) getAppSetting('rebrickable_api_key', '')) . '"></label>';
    $content .= '<button type="submit">' . htmlspecialchars(t('settings_rebrickable_save_button')) . '</button>';
    $content .= '</form>';

    $content .= '<h2>' . htmlspecialchars(t('image_download')) . '</h2>';
    $content .= '<p>' . htmlspecialchars(t('image_download_help')) . '</p>';
    $content .= '<form method="post" id="image-form">';
    $content .= '<label class="checkbox-label"><input type="checkbox" name="force_refresh" value="1"> ' . htmlspecialchars(t('image_force_refresh_label')) . '</label>';
    $content .= '<p class="hint">' . htmlspecialchars(t('image_force_refresh_help')) . '</p>';
    $content .= '<div class="import-status" id="imageStatus">';
    $content .= '<div class="progress-message idle" id="imageMessage">' . htmlspecialchars(t('import_not_started')) . '</div>';
    $content .= '<div class="progress-track" id="imageProgress"><div class="progress-fill"></div></div>';
    $content .= '<ul class="import-file-list" id="imageTableList">';
    $imageTables = [
        'sets' => t('image_table_sets'),
        'minifigs' => t('image_table_minifigs'),
        'inventory_parts' => t('image_table_inventory_parts'),
    ];
    foreach ($imageTables as $tableKey => $tableLabel) {
        $content .= '<li class="import-file import-file-pending" data-table="' . htmlspecialchars($tableKey) . '"><span class="import-file-name">' . htmlspecialchars($tableLabel) . '</span><span class="import-file-status">' . htmlspecialchars(t('import_stage_pending')) . '</span></li>';
    }
    $content .= '</ul>';
    $content .= '</div>';
    $content .= '<button type="submit">' . htmlspecialchars(t('image_download_button')) . '</button>';
    $content .= '</form>';
    $imageLabelsJson = json_encode([
        'running' => t('image_download_running'),
        'button' => t('image_download_button'),
        'resume_button' => t('import_resume_button'),
        'error_retry' => t('import_error_retry'),
        'started' => t('import_started'),
        'stage_pending' => t('import_stage_pending'),
        'stage_running' => t('image_stage_running'),
        'stage_done' => t('import_stage_done'),
        'processed_of_total' => t('image_processed_of_total'),
        'downloaded_label' => t('image_downloaded_label'),
        'skipped_label' => t('image_skipped_label'),
        'errors_label' => t('image_errors_label'),
    ], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT);
    $content .= <<<SCRIPT
<script>
(function(){
  var texts = $imageLabelsJson;
  var stageLabels = {
    pending: texts.stage_pending,
    running: texts.stage_running,
    done: texts.stage_done
  };
  var form = document.getElementById("image-form");
  var track = document.getElementById("imageProgress");
  var fill = track ? track.querySelector(".progress-fill") : null;
  var msg = document.getElementById("imageMessage");
  var tableList = document.getElementById("imageTableList");
  if (!form || !track || !fill || !msg || !tableList) {
    return;
  }

  function formatNumber(n) {
    if (n === null || n === undefined) {
      return "0";
    }
    return String(n).replace(/\\B(?=(\\d{3})+(?!\\d))/g, ".");
  }

  function renderTables(tables) {
    tableList.innerHTML = "";
    Object.keys(tables).forEach(function(key) {
      var table = tables[key];
      var li = document.createElement("li");
      li.className = "import-file import-file-" + (table.stage === "done" ? "done" : (table.stage === "running" ? "importing" : "pending"));

      var name = document.createElement("span");
      name.className = "import-file-name";
      name.textContent = key;

      var status = document.createElement("span");
      status.className = "import-file-status";
      var text = stageLabels[table.stage] || table.stage;
      if (table.stage !== "pending") {
        text += " — " + texts.processed_of_total
          .replace("{processed}", formatNumber(table.processed))
          .replace("{total}", formatNumber(table.total));
        text += " (" + texts.downloaded_label + ": " + formatNumber(table.downloaded)
          + ", " + texts.skipped_label + ": " + formatNumber(table.skipped)
          + ", " + texts.errors_label + ": " + formatNumber(table.errors) + ")";
      }
      status.textContent = text;

      li.appendChild(name);
      li.appendChild(status);
      tableList.appendChild(li);
    });
  }

  function updateStatus(data) {
    msg.classList.remove("idle");
    msg.textContent = data.message || texts.running;
    fill.style.width = (data.percent || 0) + "%";
    if (data.tables) {
      renderTables(data.tables);
    }
  }

  async function tick(formData) {
    var response = await fetch('?page=settings', {
      method: 'POST',
      body: formData,
      credentials: 'same-origin'
    });
    if (!response.ok && response.status !== 500) {
      throw new Error('tick failed with status ' + response.status);
    }
    return await response.json();
  }

  var hasStarted = false;
  var consecutiveFailures = 0;
  var maxAutoRetries = 4;

  form.addEventListener("submit", function(event) {
    event.preventDefault();
    var submitButton = form.querySelector("button[type=submit]");
    if (submitButton) {
      submitButton.disabled = true;
      submitButton.textContent = texts.running;
    }

    if (!hasStarted) {
      updateStatus({percent: 0, message: texts.started, tables: {}});
      hasStarted = true;
    } else if (msg) {
      msg.textContent = texts.running;
    }

    var baseFormData = new FormData(form);
    baseFormData.set('action', 'image_tick');
    if (!form.querySelector('input[name=force_refresh]').checked) {
      baseFormData.delete('force_refresh');
    }

    function pauseWithMessage(message) {
      if (submitButton) {
        submitButton.disabled = false;
        submitButton.textContent = texts.resume_button;
      }
      if (msg) {
        msg.textContent = message || texts.error_retry;
      }
    }

    function loop() {
      tick(baseFormData).then(function(data) {
        consecutiveFailures = 0;
        updateStatus(data);
        if (data.status === 'done') {
          if (submitButton) {
            submitButton.disabled = false;
            submitButton.textContent = texts.button;
          }
          return;
        }
        if (data.status === 'error') {
          pauseWithMessage(data.message);
          return;
        }
        setTimeout(loop, 50);
      }).catch(function() {
        consecutiveFailures++;
        if (consecutiveFailures <= maxAutoRetries) {
          if (msg) {
            msg.textContent = texts.error_retry + ' (' + consecutiveFailures + '/' + maxAutoRetries + ')';
          }
          setTimeout(loop, 1000 * consecutiveFailures);
          return;
        }
        pauseWithMessage(texts.error_retry);
      });
    }

    loop();
  });
})();
</script>
SCRIPT;

    $content .= '<h2>' . htmlspecialchars(t('update_title')) . '</h2>';
    $content .= '<p>' . htmlspecialchars(t('update_current_version', ['version' => getCurrentVersion()])) . '</p>';
    $content .= '<p class="hint">' . htmlspecialchars(t('update_warning')) . '</p>';
    $content .= '<button type="button" id="update-check-button">' . htmlspecialchars(t('update_check_button')) . '</button>';
    $content .= '<div id="update-info" style="display:none; margin-top: 1rem;"></div>';
    $content .= '<div class="import-status" id="updateStatus" style="display:none;">';
    $content .= '<div class="progress-message" id="updateMessage"></div>';
    $content .= '<div class="progress-track" id="updateProgress"><div class="progress-fill"></div></div>';
    $content .= '</div>';
    $content .= '<button type="button" id="update-apply-button" style="display:none; margin-top: 1rem;">' . htmlspecialchars(t('update_apply_button')) . '</button>';
    $updateLabelsJson = json_encode([
        'checking' => t('update_checking'),
        'checkButton' => t('update_check_button'),
        'upToDate' => t('update_up_to_date'),
        'checkFailed' => t('update_check_failed'),
        'available' => t('update_available'),
        'applyButton' => t('update_apply_button'),
        'running' => t('update_running'),
        'errorRetry' => t('import_error_retry'),
        'resumeButton' => t('import_resume_button'),
        'stageDownloading' => t('update_stage_downloading'),
        'stageExtracting' => t('update_stage_extracting'),
        'stageDiffing' => t('update_stage_diffing'),
        'stageCopying' => t('update_stage_copying'),
        'stageDeleting' => t('update_stage_deleting'),
        'stageMigrating' => t('update_stage_migrating'),
        'stageDone' => t('update_stage_done'),
        'reloadNotice' => t('update_reload_notice'),
    ], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT);
    $content .= <<<SCRIPT
<script>
(function(){
  var texts = $updateLabelsJson;
  var checkButton = document.getElementById("update-check-button");
  var infoBox = document.getElementById("update-info");
  var applyButton = document.getElementById("update-apply-button");
  var statusWrap = document.getElementById("updateStatus");
  var msg = document.getElementById("updateMessage");
  var track = document.getElementById("updateProgress");
  var fill = track ? track.querySelector(".progress-fill") : null;
  if (!checkButton || !infoBox || !applyButton || !statusWrap || !msg || !fill) {
    return;
  }

  function stageText(data) {
    switch (data.stage) {
      case "downloading":
        return texts.stageDownloading;
      case "extracting":
        return texts.stageExtracting;
      case "diffing":
        return texts.stageDiffing;
      case "copying":
        return texts.stageCopying + " (" + data.filesToCopyDone + "/" + data.filesToCopyTotal + ")";
      case "deleting":
        return texts.stageDeleting + " (" + data.filesToDeleteDone + "/" + data.filesToDeleteTotal + ")";
      case "migrating":
        return texts.stageMigrating;
      case "done":
        return texts.stageDone;
      default:
        return texts.running;
    }
  }

  checkButton.addEventListener("click", function() {
    checkButton.disabled = true;
    checkButton.textContent = texts.checking;
    infoBox.style.display = "none";

    var formData = new FormData();
    formData.set("action", "check_update");

    fetch("?page=settings", { method: "POST", body: formData, credentials: "same-origin" })
      .then(function(r) { return r.json(); })
      .then(function(data) {
        checkButton.disabled = false;
        checkButton.textContent = texts.checkButton;
        infoBox.style.display = "block";
        if (data.available && data.release) {
          infoBox.textContent = texts.available.replace("{version}", data.release.version);
          applyButton.style.display = "inline-block";
        } else if (data.error) {
          infoBox.textContent = texts.checkFailed;
          applyButton.style.display = "none";
        } else {
          infoBox.textContent = texts.upToDate;
          applyButton.style.display = "none";
        }
      })
      .catch(function() {
        checkButton.disabled = false;
        checkButton.textContent = texts.checkButton;
        infoBox.style.display = "block";
        infoBox.textContent = texts.checkFailed;
      });
  });

  var consecutiveFailures = 0;
  var maxAutoRetries = 4;

  applyButton.addEventListener("click", function() {
    applyButton.disabled = true;
    applyButton.textContent = texts.running;
    statusWrap.style.display = "block";
    msg.textContent = texts.running;
    fill.style.width = "0%";

    var formData = new FormData();
    formData.set("action", "update_tick");

    function pauseWithMessage(message) {
      applyButton.disabled = false;
      applyButton.textContent = texts.resumeButton;
      msg.textContent = message || texts.errorRetry;
    }

    function loop() {
      fetch("?page=settings", { method: "POST", body: formData, credentials: "same-origin" })
        .then(function(r) {
          if (!r.ok && r.status !== 500) {
            throw new Error("tick failed with status " + r.status);
          }
          return r.json();
        })
        .then(function(data) {
          consecutiveFailures = 0;
          if (data.status === "error") {
            pauseWithMessage(data.message);
            return;
          }
          fill.style.width = (data.percent || 0) + "%";
          msg.textContent = stageText(data);
          if (data.status === "done") {
            msg.textContent = texts.reloadNotice;
            setTimeout(function() { window.location.reload(); }, 800);
            return;
          }
          setTimeout(loop, 50);
        })
        .catch(function() {
          consecutiveFailures++;
          if (consecutiveFailures <= maxAutoRetries) {
            msg.textContent = texts.errorRetry + " (" + consecutiveFailures + "/" + maxAutoRetries + ")";
            setTimeout(loop, 1000 * consecutiveFailures);
            return;
          }
          pauseWithMessage(texts.errorRetry);
        });
    }

    loop();
  });
})();
</script>
SCRIPT;

    renderApp(t('settings_title'), $content, $user, computeAppStats($pdo));
    exit;
}

if (isset($_GET['page']) && $_GET['page'] === 'locations') {
    $editId = isset($_GET['edit']) ? (int) $_GET['edit'] : null;
    $editLocation = $editId !== null ? getStorageLocation($editId) : null;

    $content = '<h1>' . htmlspecialchars(t('locations_title')) . '</h1>';
    $content .= '<p><a href="' . $_SERVER['PHP_SELF'] . '">' . htmlspecialchars(t('settings_back')) . '</a></p>';
    $content .= '<p>' . htmlspecialchars(t('locations_help')) . '</p>';
    if ($locationMessage !== '') {
        $content .= '<p><strong>' . htmlspecialchars($locationMessage) . '</strong></p>';
    }

    $locationOptions = getStorageLocationOptions();
    $types = getLocationTypes();
    $isEdit = $editLocation !== null;

    $content .= '<section class="card"><h2>' . htmlspecialchars($isEdit ? t('location_edit_title') : t('location_add_title')) . '</h2>';
    $content .= '<form method="post" id="location-form">';
    if ($isEdit) {
        $content .= '<input type="hidden" name="action" value="rename_location">';
        $content .= '<input type="hidden" name="location_id" value="' . (int) $editLocation['id'] . '">';
    } else {
        $content .= '<input type="hidden" name="action" value="add_location">';
        $content .= '<label>' . htmlspecialchars(t('location_parent_label')) . '<select name="parent_id">';
        $content .= '<option value="">' . htmlspecialchars(t('location_parent_none')) . '</option>';
        foreach ($locationOptions as $optId => $optLabel) {
            $content .= '<option value="' . $optId . '">' . htmlspecialchars($optLabel) . '</option>';
        }
        $content .= '</select></label>';
    }
    $content .= '<label>' . htmlspecialchars(t('location_name_label')) . '<input name="name" value="' . htmlspecialchars($isEdit ? $editLocation['name'] : '') . '" required></label>';
    $content .= '<label>' . htmlspecialchars(t('location_type_label')) . '<select name="type" id="location-type-select">';
    $content .= '<option value="">' . htmlspecialchars(t('location_type_none')) . '</option>';
    $currentType = $isEdit ? $editLocation['location_type'] : null;
    foreach ($types as $typeKey => $typeConfig) {
        $selected = $typeKey === $currentType ? ' selected' : '';
        $content .= '<option value="' . htmlspecialchars($typeKey) . '"' . $selected . '>' . htmlspecialchars(t($typeConfig['labelKey'])) . '</option>';
    }
    $content .= '</select></label>';

    if (!$isEdit) {
        $content .= '<div id="location-bulk-fields" style="display:none;">';
        $content .= '<label>' . htmlspecialchars(t('location_bulk_count_label')) . '<input type="number" name="child_count" min="0" value="0"></label>';
        $content .= '<label>' . htmlspecialchars(t('location_bulk_naming_label')) . '<input type="text" name="naming_pattern" id="location-naming-pattern" value=""></label>';
        $content .= '</div>';
    }

    $content .= '<button type="submit">' . htmlspecialchars($isEdit ? t('location_save_button') : t('location_add_button')) . '</button>';
    if ($isEdit) {
        $content .= ' <a href="?page=locations">' . htmlspecialchars(t('location_cancel_edit')) . '</a>';
    }
    $content .= '</form></section>';

    if (!$isEdit) {
        $bulkPatterns = [];
        foreach ($types as $typeKey => $typeConfig) {
            $bulkPatterns[$typeKey] = $typeConfig['bulkChildKey'] !== null ? t($typeConfig['bulkChildKey']) : null;
        }
        $bulkPatternsJson = json_encode($bulkPatterns, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT);
        $content .= <<<SCRIPT
<script>
(function(){
  var patterns = $bulkPatternsJson;
  var typeSelect = document.getElementById("location-type-select");
  var bulkFields = document.getElementById("location-bulk-fields");
  var namingInput = document.getElementById("location-naming-pattern");
  if (!typeSelect || !bulkFields || !namingInput) {
    return;
  }
  function update() {
    var pattern = patterns[typeSelect.value];
    if (pattern) {
      bulkFields.style.display = "block";
      namingInput.value = pattern;
    } else {
      bulkFields.style.display = "none";
      namingInput.value = "";
    }
  }
  typeSelect.addEventListener("change", update);
  update();
})();
</script>
SCRIPT;
    }

    $content .= '<section class="card"><h2>' . htmlspecialchars(t('locations_tree_title')) . '</h2>';
    $tree = getStorageLocationTree();
    if (empty($tree)) {
        $content .= '<p>' . htmlspecialchars(t('locations_tree_empty')) . '</p>';
    } else {
        $renderNode = function (array $nodes) use (&$renderNode, $types): string {
            $html = '<ul class="location-tree">';
            foreach ($nodes as $node) {
                $typeLabel = $node['location_type'] !== null && isset($types[$node['location_type']])
                    ? t($types[$node['location_type']]['labelKey'])
                    : '';
                $html .= '<li>';
                $html .= '<span class="location-name">' . htmlspecialchars($node['name']) . '</span>';
                if ($typeLabel !== '') {
                    $html .= ' <span class="location-type-badge">' . htmlspecialchars($typeLabel) . '</span>';
                }
                $html .= ' <a href="?page=locations&edit=' . (int) $node['id'] . '">' . htmlspecialchars(t('location_edit_link')) . '</a>';
                $html .= ' <form method="post" class="location-delete-form"><input type="hidden" name="action" value="delete_location"><input type="hidden" name="location_id" value="' . (int) $node['id'] . '"><button type="submit" class="link-button">' . htmlspecialchars(t('location_delete_link')) . '</button></form>';
                if (!empty($node['children'])) {
                    $html .= $renderNode($node['children']);
                }
                $html .= '</li>';
            }
            $html .= '</ul>';
            return $html;
        };
        $content .= $renderNode($tree);
    }
    $content .= '</section>';

    renderApp(t('locations_title'), $content, $user, computeAppStats($pdo));
    exit;
}

if (isset($_GET['page']) && $_GET['page'] === 'bricks_search') {
    $searchQuery = trim((string) ($_GET['q'] ?? ''));
    $selectedCategories = array_values(array_filter(array_map('strval', (array) ($_GET['category'] ?? []))));
    $selectedColors = array_values(array_filter(array_map('strval', (array) ($_GET['color'] ?? []))));
    $hidePrinted = ($_GET['hide_printed'] ?? '') === '1';
    $pageNum = max(1, (int) ($_GET['p'] ?? 1));
    $perPage = PARTS_SEARCH_PAGE_SIZE;
    $isBrowsing = $searchQuery === '' && empty($selectedCategories) && empty($selectedColors);

    $renderPartCard = function (array $part): string {
        $html = '<div class="part-card" data-part-id="' . (int) $part['id'] . '" role="button" tabindex="0">';
        $html .= '<span class="part-card-image">' . ($part['thumbnail'] !== null ? '<img src="' . htmlspecialchars($part['thumbnail']) . '" alt="">' : getNavIcon('bricks')) . '</span>';
        $html .= '<span class="part-card-num">' . htmlspecialchars($part['part_num']) . '</span>';
        $html .= '<span class="part-card-name" title="' . htmlspecialchars($part['name']) . '">' . htmlspecialchars($part['name']) . '</span>';
        $html .= '</div>';
        return $html;
    };

    // Infinite-scroll continuation request: return just the next batch of
    // cards as JSON instead of a full page render.
    if (!$isBrowsing && ($_GET['ajax'] ?? '') === '1') {
        header('Content-Type: application/json');
        $results = searchParts($pdo, $searchQuery, $selectedCategories, $selectedColors, $hidePrinted, $pageNum, $perPage);
        $results['items'] = applyPartTranslations($pdo, $results['items'], getLocale());
        $html = '';
        foreach ($results['items'] as $part) {
            $html .= $renderPartCard($part);
        }
        $hasMore = ($pageNum * $perPage) < $results['total'];
        echo json_encode(['html' => $html, 'hasMore' => $hasMore], JSON_UNESCAPED_UNICODE);
        exit;
    }

    $filterParams = ['page' => 'bricks_search'];
    if ($searchQuery !== '') {
        $filterParams['q'] = $searchQuery;
    }
    if (!empty($selectedCategories)) {
        $filterParams['category'] = $selectedCategories;
    }
    if (!empty($selectedColors)) {
        $filterParams['color'] = $selectedColors;
    }
    if ($hidePrinted) {
        $filterParams['hide_printed'] = '1';
    }

    $renderHiddenFields = function (array $params, array $exclude) {
        $html = '';
        foreach ($params as $key => $value) {
            if (in_array($key, $exclude, true)) {
                continue;
            }
            foreach ((array) $value as $singleValue) {
                $name = is_array($value) ? $key . '[]' : $key;
                $html .= '<input type="hidden" name="' . htmlspecialchars($name) . '" value="' . htmlspecialchars((string) $singleValue) . '">';
            }
        }
        return $html;
    };

    $content = '<h1>' . htmlspecialchars(t('nav_bricks_search')) . '</h1>';

    $content .= '<form method="get" action="' . htmlspecialchars($_SERVER['PHP_SELF']) . '" class="parts-search-form">';
    $content .= '<input type="hidden" name="page" value="bricks_search">';
    $content .= $renderHiddenFields($filterParams, ['page', 'q']);
    $content .= '<input type="text" name="q" value="' . htmlspecialchars($searchQuery) . '" placeholder="' . htmlspecialchars(t('parts_search_placeholder')) . '">';
    $content .= '<button type="submit">' . htmlspecialchars(t('search_button')) . '</button>';
    $content .= '</form>';

    if ($isBrowsing) {
        $tileFilter = trim((string) ($_GET['tilefilter'] ?? 'all'));
        if ($tileFilter === 'popular') {
            $categories = getPopularPartCategories($pdo, PARTS_POPULAR_CATEGORY_LIMIT);
        } elseif ($tileFilter === 'minifigs') {
            $categories = array_values(array_filter(getPartCategories($pdo), function ($c) {
                return stripos($c['name'], 'minifig') !== false;
            }));
        } elseif ($tileFilter === 'technic') {
            $categories = array_values(array_filter(getPartCategories($pdo), function ($c) {
                return stripos($c['name'], 'technic') !== false;
            }));
        } else {
            $categories = getPartCategories($pdo);
        }

        $content .= '<p class="tile-filter-row">' . htmlspecialchars(t('tile_filter_label')) . ': ';
        $tileFilters = ['popular' => 'tile_filter_popular', 'minifigs' => 'tile_filter_minifigs', 'technic' => 'tile_filter_technic', 'old' => 'tile_filter_old', 'all' => 'tile_filter_all'];
        $filterLinks = [];
        foreach ($tileFilters as $filterKey => $filterLabelKey) {
            $activeClass = $filterKey === $tileFilter ? ' class="active"' : '';
            $filterLinks[] = '<a' . $activeClass . ' href="?page=bricks_search&tilefilter=' . $filterKey . '">' . htmlspecialchars(t($filterLabelKey)) . '</a>';
        }
        $content .= implode(' | ', $filterLinks);
        $content .= '</p>';

        if (empty($categories)) {
            $content .= '<section class="card"><p>' . htmlspecialchars(t('parts_categories_empty')) . '</p></section>';
        } else {
            $tileImages = getCategoryTileImages($pdo, array_map(function ($c) {
                return (string) $c['part_cat_id'];
            }, $categories));
            $content .= '<div class="category-tile-grid">';
            foreach ($categories as $cat) {
                $img = $tileImages[(string) $cat['part_cat_id']] ?? null;
                $content .= '<a class="category-tile" href="?page=bricks_search&category%5B%5D=' . urlencode((string) $cat['part_cat_id']) . '">';
                $content .= '<span class="category-tile-image">' . ($img !== null ? '<img src="' . htmlspecialchars($img) . '" alt="">' : getNavIcon('bricks')) . '</span>';
                $content .= '<span class="category-tile-label">' . htmlspecialchars($cat['name']) . '</span>';
                $content .= '</a>';
            }
            $content .= '</div>';
        }
    } else {
        $results = searchParts($pdo, $searchQuery, $selectedCategories, $selectedColors, $hidePrinted, 1, $perPage);
        $results['items'] = applyPartTranslations($pdo, $results['items'], getLocale());

        $sidebar = '<form method="get" action="' . htmlspecialchars($_SERVER['PHP_SELF']) . '" class="parts-filter-sidebar">';
        $sidebar .= '<input type="hidden" name="page" value="bricks_search">';
        $sidebar .= $renderHiddenFields($filterParams, ['page', 'category', 'color', 'hide_printed']);

        $sidebar .= '<div class="filter-group"><h3>' . htmlspecialchars(t('filter_category_title')) . '</h3><div class="filter-options">';
        foreach (getPartCategoriesWithCounts($pdo) as $cat) {
            $catIdStr = (string) $cat['part_cat_id'];
            $checked = in_array($catIdStr, $selectedCategories, true) ? ' checked' : '';
            $sidebar .= '<label class="filter-checkbox"><input type="checkbox" name="category[]" value="' . htmlspecialchars($catIdStr) . '"' . $checked . '> ' . htmlspecialchars($cat['name']) . ' <span class="filter-count">(' . (int) $cat['cnt'] . ')</span></label>';
        }
        $sidebar .= '</div></div>';

        $sidebar .= '<div class="filter-group"><h3>' . htmlspecialchars(t('filter_color_title')) . '</h3><div class="filter-options">';
        foreach (getColorFacet($pdo) as $color) {
            $colorIdStr = (string) $color['color_id'];
            $checked = in_array($colorIdStr, $selectedColors, true) ? ' checked' : '';
            $rgb = (string) ($color['rgb'] ?? '');
            $swatch = $rgb !== '' ? '#' . ltrim($rgb, '#') : '#cccccc';
            $sidebar .= '<label class="filter-checkbox"><input type="checkbox" name="color[]" value="' . htmlspecialchars($colorIdStr) . '"' . $checked . '> <span class="color-swatch" style="background-color:' . htmlspecialchars($swatch) . '"></span>' . htmlspecialchars($color['name']) . ' <span class="filter-count">(' . (int) $color['cnt'] . ')</span></label>';
        }
        $sidebar .= '</div></div>';

        $sidebar .= '<div class="filter-group"><label class="filter-checkbox"><input type="checkbox" name="hide_printed" value="1"' . ($hidePrinted ? ' checked' : '') . '> ' . htmlspecialchars(t('filter_hide_printed')) . '</label></div>';

        $sidebar .= '<button type="submit" class="filter-apply-button">' . htmlspecialchars(t('filter_apply_button')) . '</button>';
        $sidebar .= '</form>';

        $main = '<p><a href="?page=bricks_search">&larr; ' . htmlspecialchars(t('back_to_categories')) . '</a></p>';
        $main .= '<span class="results-summary">' . htmlspecialchars(t('parts_found_count', ['count' => number_format($results['total'])])) . '</span>';

        if (empty($results['items'])) {
            $main .= '<section class="card"><p>' . htmlspecialchars(t('parts_categories_empty')) . '</p></section>';
        } else {
            $hasMore = $perPage < $results['total'];
            $main .= '<div class="parts-grid" id="parts-grid">';
            foreach ($results['items'] as $part) {
                $main .= $renderPartCard($part);
            }
            $main .= '</div>';
            $main .= '<div id="parts-load-sentinel" class="parts-load-sentinel" data-has-more="' . ($hasMore ? '1' : '0') . '" data-next-page="2">';
            $main .= '<span class="parts-load-status" data-loading-text="' . htmlspecialchars(t('parts_loading_more')) . '" data-end-text="' . htmlspecialchars(t('parts_no_more')) . '">' . ($hasMore ? '' : htmlspecialchars(t('parts_no_more'))) . '</span>';
            $main .= '</div>';
            $main .= <<<SCRIPT
<script>
(function(){
  var sentinel = document.getElementById('parts-load-sentinel');
  var grid = document.getElementById('parts-grid');
  var status = sentinel ? sentinel.querySelector('.parts-load-status') : null;
  if (!sentinel || !grid || !status) {
    return;
  }
  var loading = false;

  function loadMore() {
    if (loading || sentinel.dataset.hasMore !== '1') {
      return;
    }
    loading = true;
    status.textContent = status.dataset.loadingText;

    var params = new URLSearchParams(window.location.search);
    params.set('ajax', '1');
    params.set('p', sentinel.dataset.nextPage);

    fetch('?' + params.toString(), { credentials: 'same-origin' })
      .then(function(r) { return r.json(); })
      .then(function(data) {
        grid.insertAdjacentHTML('beforeend', data.html);
        sentinel.dataset.hasMore = data.hasMore ? '1' : '0';
        sentinel.dataset.nextPage = String(parseInt(sentinel.dataset.nextPage, 10) + 1);
        status.textContent = data.hasMore ? '' : status.dataset.endText;
        loading = false;
        if (data.hasMore) {
          checkAndLoad();
        }
      })
      .catch(function() {
        loading = false;
      });
  }

  function checkAndLoad() {
    var rect = sentinel.getBoundingClientRect();
    if (rect.top < window.innerHeight + 400) {
      loadMore();
    }
  }

  if ('IntersectionObserver' in window) {
    var observer = new IntersectionObserver(function(entries) {
      entries.forEach(function(entry) {
        if (entry.isIntersecting) {
          loadMore();
        }
      });
    }, { rootMargin: '400px' });
    observer.observe(sentinel);
  } else {
    window.addEventListener('scroll', checkAndLoad);
    checkAndLoad();
  }
})();
</script>
SCRIPT;
        }

        $main .= '<div class="modal-overlay" id="part-detail-modal" style="display:none;">';
        $main .= '<div class="modal-box"><button type="button" class="modal-close" id="part-modal-close" aria-label="' . htmlspecialchars(t('close_button')) . '"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><path d="M5 5l14 14M19 5L5 19"/></svg></button>';
        $main .= '<div id="part-modal-content"></div>';
        $main .= '</div></div>';

        $modalLabelsJson = json_encode([
            'notFound' => t('part_not_found'),
            'appearsInSets' => t('part_appears_in_sets'),
            'appearsInNoSets' => t('part_appears_in_no_sets'),
            'bricklinkLink' => t('bricklink_link'),
            'brickowlLink' => t('brickowl_link'),
            'addToInventoryTitle' => t('add_to_inventory_title'),
            'colorLabel' => t('filter_color_title'),
            'knownColorsTitle' => t('add_stock_known_colors_title'),
            'quantityLabel' => t('add_stock_quantity_label'),
            'conditionLabel' => t('add_stock_condition_label'),
            'conditionNew' => t('condition_new'),
            'conditionUsed' => t('condition_used'),
            'level1Label' => t('add_stock_level1_label'),
            'level2Label' => t('add_stock_level2_label'),
            'level3Label' => t('add_stock_level3_label'),
            'selectPlaceholder' => t('add_stock_select_placeholder'),
            'noChildren' => t('add_stock_no_children'),
            'printOfLabel' => t('print_of_label'),
            'colorOtherGroupLabel' => t('color_other_group_label'),
            'partSetsTitle' => t('part_sets_title'),
            'backToPart' => t('back_to_part'),
            'translationAddButton' => t('translation_add_button'),
            'translationEditButton' => t('translation_edit_button'),
            'translationSaveButton' => t('translation_save_button'),
            'translationCancelButton' => t('translation_cancel_button'),
            'translationOriginalLabel' => t('translation_original_name_label'),
            'translationPlaceholder' => t('translation_placeholder'),
            'addButton' => t('add_stock_button'),
            'errorRetry' => t('import_error_retry'),
        ], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT);

        $main .= <<<SCRIPT
<script>
(function(){
  var texts = $modalLabelsJson;
  var modal = document.getElementById('part-detail-modal');
  var content = document.getElementById('part-modal-content');
  var closeBtn = document.getElementById('part-modal-close');
  var grid = document.getElementById('parts-grid');
  if (!modal || !content || !closeBtn || !grid) {
    return;
  }

  function closeModal() {
    modal.style.display = 'none';
    content.innerHTML = '';
  }

  closeBtn.addEventListener('click', closeModal);
  modal.addEventListener('click', function(e) {
    if (e.target === modal) {
      closeModal();
    }
  });
  document.addEventListener('keydown', function(e) {
    if (e.key === 'Escape' && modal.style.display !== 'none') {
      closeModal();
    }
  });

  function buildLevelSelect(labelText, level) {
    var wrap = document.createElement('div');
    wrap.className = 'location-level';
    var labelSpan = document.createElement('span');
    labelSpan.className = 'location-level-label';
    labelSpan.textContent = labelText;
    wrap.appendChild(labelSpan);
    var select = document.createElement('select');
    select.dataset.level = level;
    select.innerHTML = '<option value="">' + texts.selectPlaceholder + '</option>';
    wrap.appendChild(select);
    var hint = document.createElement('span');
    hint.className = 'location-hint';
    wrap.appendChild(hint);
    return wrap;
  }

  function fillLocationSelect(select, hint, parentId, callback) {
    hint.textContent = '';
    var params = new URLSearchParams();
    params.set('action', 'location_children');
    if (parentId !== null) {
      params.set('parent_id', parentId);
    }
    fetch('?' + params.toString(), { credentials: 'same-origin' })
      .then(function(r) { return r.json(); })
      .then(function(data) {
        select.innerHTML = '<option value="">' + texts.selectPlaceholder + '</option>';
        (data.children || []).forEach(function(loc) {
          var opt = document.createElement('option');
          opt.value = loc.id;
          opt.textContent = loc.name;
          select.appendChild(opt);
        });
        var hasChildren = (data.children || []).length > 0;
        select.disabled = !hasChildren;
        if (!hasChildren) {
          hint.textContent = texts.noChildren;
        }
        if (callback) {
          callback();
        }
      })
      .catch(function() {
        hint.textContent = texts.errorRetry;
      });
  }

  function openPartModal(partId) {
    content.innerHTML = '';
    modal.style.display = 'flex';

    fetch('?action=part_detail&part_id=' + encodeURIComponent(partId), { credentials: 'same-origin' })
      .then(function(r) { return r.json(); })
      .then(function(data) {
        if (data.error) {
          content.innerHTML = '<p>' + texts.notFound + '</p>';
          return;
        }
        renderPartModal(data);
      })
      .catch(function() {
        content.innerHTML = '<p>' + texts.errorRetry + '</p>';
      });
  }

  function openPartSetsList(part) {
    content.innerHTML = '';

    var backLink = document.createElement('a');
    backLink.href = '#';
    backLink.className = 'part-sets-back';
    backLink.textContent = texts.backToPart;
    backLink.addEventListener('click', function(e) {
      e.preventDefault();
      openPartModal(part.id);
    });
    content.appendChild(backLink);

    var title = document.createElement('h3');
    title.textContent = texts.partSetsTitle;
    content.appendChild(title);

    var list = document.createElement('div');
    list.className = 'part-sets-list';
    content.appendChild(list);

    fetch('?action=part_sets&part_id=' + encodeURIComponent(part.id), { credentials: 'same-origin' })
      .then(function(r) { return r.json(); })
      .then(function(data) {
        (data.sets || []).forEach(function(set) {
          var row = document.createElement('div');
          row.className = 'part-sets-row';

          var thumb = document.createElement('span');
          thumb.className = 'part-sets-thumb';
          thumb.innerHTML = set.thumbnail
            ? '<img src="' + set.thumbnail + '" alt="">'
            : content.dataset.fallbackIcon || '';
          row.appendChild(thumb);

          var setInfo = document.createElement('span');
          setInfo.className = 'part-sets-info';
          var setName = document.createElement('span');
          setName.className = 'part-sets-name';
          setName.textContent = (set.name || set.set_num) + (set.year ? ' (' + set.year + ')' : '');
          var setMeta = document.createElement('span');
          setMeta.className = 'part-sets-meta';
          setMeta.textContent = set.set_num + ' · ' + set.quantity + 'x';
          setInfo.appendChild(setName);
          setInfo.appendChild(setMeta);
          row.appendChild(setInfo);

          list.appendChild(row);
        });
      })
      .catch(function() {
        list.textContent = texts.errorRetry;
      });
  }

  function renderPartModal(data) {
    var part = data.part;
    content.innerHTML = '';

    var header = document.createElement('div');
    header.className = 'part-modal-header';

    var img = document.createElement('div');
    img.className = 'part-modal-image';
    img.innerHTML = part.thumbnail
      ? '<img src="' + part.thumbnail + '" alt="">'
      : content.dataset.fallbackIcon || '';
    header.appendChild(img);

    var info = document.createElement('div');
    info.className = 'part-modal-info';
    var title = document.createElement('h2');
    title.textContent = part.translated_name || part.name;

    var originalName = null;
    if (part.translated_name) {
      originalName = document.createElement('p');
      originalName.className = 'part-modal-original-name';
      originalName.textContent = texts.translationOriginalLabel + ': ' + part.name;
    }

    var meta = document.createElement('p');
    meta.className = 'part-modal-meta';
    meta.textContent = part.part_num + (part.category_name ? ' · ' + part.category_name : '');

    var links = document.createElement('p');
    links.className = 'part-modal-links';
    var blLink = document.createElement('a');
    blLink.href = part.bricklink_url;
    blLink.target = '_blank';
    blLink.rel = 'noopener';
    blLink.textContent = texts.bricklinkLink;
    var boLink = document.createElement('a');
    boLink.href = part.brickowl_url;
    boLink.target = '_blank';
    boLink.rel = 'noopener';
    boLink.textContent = texts.brickowlLink;
    links.appendChild(blLink);
    links.appendChild(document.createTextNode(' · '));
    links.appendChild(boLink);

    var sets = document.createElement('p');
    sets.className = 'part-modal-sets';
    var setsText = texts.appearsInSets
      .replace('{total}', part.total_appearances)
      .replace('{count}', part.sets_count)
      .replace('{minYear}', part.min_year)
      .replace('{maxYear}', part.max_year);
    if (part.sets_count > 0) {
      var setsLink = document.createElement('a');
      setsLink.href = '#';
      setsLink.textContent = setsText;
      setsLink.addEventListener('click', function(e) {
        e.preventDefault();
        openPartSetsList(part);
      });
      sets.appendChild(setsLink);
    } else {
      sets.textContent = texts.appearsInNoSets;
    }

    info.appendChild(title);
    if (originalName) {
      info.appendChild(originalName);
    }
    info.appendChild(meta);
    info.appendChild(links);
    info.appendChild(sets);

    if (part.translation_locale !== 'en') {
      var translationSection = document.createElement('div');
      translationSection.className = 'part-modal-translation';

      var translationToggle = document.createElement('a');
      translationToggle.href = '#';
      translationToggle.textContent = part.translated_name ? texts.translationEditButton : texts.translationAddButton;

      var translationForm = document.createElement('form');
      translationForm.className = 'part-modal-translation-form';
      translationForm.style.display = 'none';

      var translationInput = document.createElement('input');
      translationInput.type = 'text';
      translationInput.value = part.translated_name || '';
      translationInput.placeholder = texts.translationPlaceholder;

      var translationSaveBtn = document.createElement('button');
      translationSaveBtn.type = 'submit';
      translationSaveBtn.textContent = texts.translationSaveButton;

      var translationCancelBtn = document.createElement('button');
      translationCancelBtn.type = 'button';
      translationCancelBtn.textContent = texts.translationCancelButton;

      var translationMsg = document.createElement('span');
      translationMsg.className = 'part-modal-translation-message';

      translationForm.appendChild(translationInput);
      translationForm.appendChild(translationSaveBtn);
      translationForm.appendChild(translationCancelBtn);
      translationForm.appendChild(translationMsg);

      translationToggle.addEventListener('click', function(e) {
        e.preventDefault();
        translationToggle.style.display = 'none';
        translationForm.style.display = 'flex';
        translationInput.focus();
      });
      translationCancelBtn.addEventListener('click', function() {
        translationForm.style.display = 'none';
        translationToggle.style.display = 'inline-block';
      });
      translationForm.addEventListener('submit', function(e) {
        e.preventDefault();
        translationMsg.textContent = '';
        var formData = new FormData();
        formData.set('action', 'save_part_translation');
        formData.set('part_id', part.id);
        formData.set('name', translationInput.value);
        fetch('?', { method: 'POST', body: formData, credentials: 'same-origin' })
          .then(function(r) { return r.json(); })
          .then(function(res) {
            if (res.success) {
              title.textContent = res.name;
              part.translated_name = res.name;
              translationToggle.textContent = texts.translationEditButton;
              translationForm.style.display = 'none';
              translationToggle.style.display = 'inline-block';
              if (!originalName) {
                originalName = document.createElement('p');
                originalName.className = 'part-modal-original-name';
                originalName.textContent = texts.translationOriginalLabel + ': ' + part.name;
                info.insertBefore(originalName, meta);
              }
            } else {
              translationMsg.textContent = res.message;
            }
          })
          .catch(function() {
            translationMsg.textContent = texts.errorRetry;
          });
      });

      translationSection.appendChild(translationToggle);
      translationSection.appendChild(translationForm);
      info.appendChild(translationSection);
    }

    if (data.printParent) {
      var printOf = document.createElement('p');
      printOf.className = 'part-modal-print-of';
      var printLink = document.createElement('a');
      printLink.href = '#';
      printLink.textContent = texts.printOfLabel + ': ' + data.printParent.name + ' (' + data.printParent.part_num + ')';
      printLink.addEventListener('click', function(e) {
        e.preventDefault();
        openPartModal(data.printParent.id);
      });
      printOf.appendChild(printLink);
      info.appendChild(printOf);
    }

    header.appendChild(info);
    content.appendChild(header);

    var formTitle = document.createElement('h3');
    formTitle.textContent = texts.addToInventoryTitle;
    content.appendChild(formTitle);

    var msgBox = document.createElement('div');
    msgBox.className = 'add-stock-message';
    content.appendChild(msgBox);

    var form = document.createElement('form');
    form.className = 'add-stock-form';

    var knownColors = data.knownColors || [];
    var otherColors = data.otherColors || [];
    var allPickerColors = knownColors.concat(otherColors);

    function colorSwatchStyle(c) {
      return c.rgb ? '#' + c.rgb.replace('#', '') : '#cccccc';
    }

    // Native <select>/<option> elements can't reliably show a swatch per row
    // (no HTML inside an <option> — support for even a CSS background on one
    // is inconsistent across browsers, several ignore it outright). A small
    // custom combobox gives full control over each row's layout instead.
    var colorHiddenInput = document.createElement('input');
    colorHiddenInput.type = 'hidden';
    colorHiddenInput.name = 'color_id';

    var colorLabel = document.createElement('label');
    colorLabel.textContent = texts.colorLabel;

    var combo = document.createElement('div');
    combo.className = 'color-combo';

    var comboToggle = document.createElement('button');
    comboToggle.type = 'button';
    comboToggle.className = 'color-combo-toggle';
    var comboToggleSwatch = document.createElement('span');
    comboToggleSwatch.className = 'color-combo-toggle-swatch';
    var comboToggleName = document.createElement('span');
    comboToggleName.className = 'color-combo-toggle-name';
    comboToggle.appendChild(comboToggleSwatch);
    comboToggle.appendChild(comboToggleName);

    var comboPanel = document.createElement('div');
    comboPanel.className = 'color-combo-panel';
    comboPanel.style.display = 'none';

    function updateActiveSwatch() {
      if (!swatchGrid) {
        return;
      }
      Array.prototype.forEach.call(swatchGrid.children, function(btn) {
        btn.classList.toggle('active', btn.dataset.colorId === colorHiddenInput.value);
      });
    }

    function updateComboOptionActive() {
      Array.prototype.forEach.call(comboPanel.querySelectorAll('.color-combo-option'), function(btn) {
        btn.classList.toggle('active', btn.dataset.colorId === colorHiddenInput.value);
      });
    }

    function setColorValue(c) {
      colorHiddenInput.value = String(c.id);
      comboToggleSwatch.style.backgroundColor = colorSwatchStyle(c);
      comboToggleName.textContent = c.name;
      updateActiveSwatch();
      updateComboOptionActive();
    }

    function closeCombo() {
      comboPanel.style.display = 'none';
    }

    function buildComboOption(c) {
      var opt = document.createElement('button');
      opt.type = 'button';
      opt.className = 'color-combo-option';
      opt.dataset.colorId = String(c.id);
      var optName = document.createElement('span');
      optName.className = 'color-combo-option-name';
      optName.textContent = c.name;
      var optSwatch = document.createElement('span');
      optSwatch.className = 'color-combo-option-swatch';
      optSwatch.style.backgroundColor = colorSwatchStyle(c);
      opt.appendChild(optName);
      opt.appendChild(optSwatch);
      opt.addEventListener('click', function() {
        setColorValue(c);
        closeCombo();
      });
      return opt;
    }

    knownColors.forEach(function(c) {
      comboPanel.appendChild(buildComboOption(c));
    });
    if (otherColors.length > 0) {
      var groupLabel = document.createElement('div');
      groupLabel.className = 'color-combo-group-label';
      groupLabel.textContent = texts.colorOtherGroupLabel;
      comboPanel.appendChild(groupLabel);
      otherColors.forEach(function(c) {
        comboPanel.appendChild(buildComboOption(c));
      });
    }

    comboToggle.addEventListener('click', function() {
      comboPanel.style.display = comboPanel.style.display === 'none' ? 'block' : 'none';
    });
    document.addEventListener('click', function(e) {
      if (!combo.contains(e.target)) {
        closeCombo();
      }
    });

    combo.appendChild(comboToggle);
    combo.appendChild(comboPanel);
    colorLabel.appendChild(combo);
    colorLabel.appendChild(colorHiddenInput);
    form.appendChild(colorLabel);

    var swatchGrid = null;
    if (knownColors.length > 0) {
      var swatchSection = document.createElement('div');
      swatchSection.className = 'color-swatch-section';
      var swatchTitle = document.createElement('p');
      swatchTitle.className = 'color-swatch-title';
      swatchTitle.textContent = texts.knownColorsTitle;
      swatchGrid = document.createElement('div');
      swatchGrid.className = 'color-swatch-grid';
      knownColors.forEach(function(c) {
        var swatch = document.createElement('button');
        swatch.type = 'button';
        swatch.className = 'color-swatch-btn';
        swatch.title = c.name;
        swatch.style.backgroundColor = colorSwatchStyle(c);
        swatch.dataset.colorId = String(c.id);
        swatch.addEventListener('click', function() {
          setColorValue(c);
        });
        swatchGrid.appendChild(swatch);
      });
      swatchSection.appendChild(swatchTitle);
      swatchSection.appendChild(swatchGrid);
      form.appendChild(swatchSection);
    }

    if (allPickerColors.length > 0) {
      setColorValue(allPickerColors[0]);
    }

    var qtyLabel = document.createElement('label');
    qtyLabel.textContent = texts.quantityLabel;
    var qtyInput = document.createElement('input');
    qtyInput.type = 'number';
    qtyInput.name = 'quantity';
    qtyInput.min = '1';
    qtyInput.value = '1';
    qtyLabel.appendChild(qtyInput);
    form.appendChild(qtyLabel);

    var condLabel = document.createElement('label');
    condLabel.textContent = texts.conditionLabel;
    var condSelect = document.createElement('select');
    condSelect.name = 'condition_type';
    var optUsed = document.createElement('option');
    optUsed.value = 'used';
    optUsed.textContent = texts.conditionUsed;
    optUsed.selected = true;
    var optNew = document.createElement('option');
    optNew.value = 'new';
    optNew.textContent = texts.conditionNew;
    condSelect.appendChild(optUsed);
    condSelect.appendChild(optNew);
    condLabel.appendChild(condSelect);
    form.appendChild(condLabel);

    var level1Wrap = buildLevelSelect(texts.level1Label, 1);
    var level2Wrap = buildLevelSelect(texts.level2Label, 2);
    var level3Wrap = buildLevelSelect(texts.level3Label, 3);
    var level1Select = level1Wrap.querySelector('select');
    var level2Select = level2Wrap.querySelector('select');
    var level3Select = level3Wrap.querySelector('select');
    var level1Hint = level1Wrap.querySelector('.location-hint');
    var level2Hint = level2Wrap.querySelector('.location-hint');
    var level3Hint = level3Wrap.querySelector('.location-hint');
    level2Select.disabled = true;
    level3Select.disabled = true;
    form.appendChild(level1Wrap);
    form.appendChild(level2Wrap);
    form.appendChild(level3Wrap);

    level1Select.innerHTML = '<option value="">' + texts.selectPlaceholder + '</option>';
    (data.rootLocations || []).forEach(function(loc) {
      var opt = document.createElement('option');
      opt.value = loc.id;
      opt.textContent = loc.name;
      level1Select.appendChild(opt);
    });
    if ((data.rootLocations || []).length === 0) {
      level1Hint.textContent = texts.noChildren;
    }

    level1Select.addEventListener('change', function() {
      level2Select.innerHTML = '<option value="">' + texts.selectPlaceholder + '</option>';
      level3Select.innerHTML = '<option value="">' + texts.selectPlaceholder + '</option>';
      level2Select.disabled = true;
      level3Select.disabled = true;
      level2Hint.textContent = '';
      level3Hint.textContent = '';
      if (level1Select.value) {
        fillLocationSelect(level2Select, level2Hint, level1Select.value);
      }
    });

    level2Select.addEventListener('change', function() {
      level3Select.innerHTML = '<option value="">' + texts.selectPlaceholder + '</option>';
      level3Select.disabled = true;
      level3Hint.textContent = '';
      if (level2Select.value) {
        fillLocationSelect(level3Select, level3Hint, level2Select.value);
      }
    });

    var submitBtn = document.createElement('button');
    submitBtn.type = 'submit';
    submitBtn.textContent = texts.addButton;
    form.appendChild(submitBtn);

    form.addEventListener('submit', function(e) {
      e.preventDefault();
      msgBox.textContent = '';
      msgBox.className = 'add-stock-message';
      submitBtn.disabled = true;

      var formData = new FormData();
      formData.set('action', 'add_stock');
      formData.set('part_id', part.id);
      formData.set('color_id', colorHiddenInput.value);
      formData.set('quantity', qtyInput.value);
      formData.set('condition_type', condSelect.value);
      formData.set('location_id', level3Select.value);

      fetch('?', { method: 'POST', body: formData, credentials: 'same-origin' })
        .then(function(r) { return r.json(); })
        .then(function(res) {
          submitBtn.disabled = false;
          msgBox.textContent = res.message;
          msgBox.className = 'add-stock-message ' + (res.success ? 'success' : 'error');
        })
        .catch(function() {
          submitBtn.disabled = false;
          msgBox.textContent = texts.errorRetry;
          msgBox.className = 'add-stock-message error';
        });
    });

    content.appendChild(form);
  }

  grid.addEventListener('click', function(e) {
    var card = e.target.closest('.part-card');
    if (card) {
      openPartModal(card.dataset.partId);
    }
  });
  grid.addEventListener('keydown', function(e) {
    if (e.key !== 'Enter' && e.key !== ' ') {
      return;
    }
    var card = e.target.closest('.part-card');
    if (card) {
      e.preventDefault();
      openPartModal(card.dataset.partId);
    }
  });
})();
</script>
SCRIPT;

        $content .= '<div class="parts-search-layout">' . $sidebar . '<div class="parts-search-main">' . $main . '</div></div>';
    }

    renderApp(t('nav_bricks_search'), $content, $user, computeAppStats($pdo));
    exit;
}

$stubPages = [
    'search' => 'search_scope_all',
    'sets' => 'nav_sets',
    'sets_search' => 'nav_sets_search',
    'minifigs_search' => 'nav_minifigs_search',
    'bricks' => 'nav_bricks',
    'colors_search' => 'nav_colors_search',
    'my_sets' => 'nav_my_sets',
    'my_sets_all' => 'nav_my_sets_all',
    'my_sets_themes' => 'nav_my_sets_themes',
    'my_bricks' => 'nav_my_bricks',
    'my_bricks_all' => 'nav_my_bricks_all',
    'my_bricks_by_location' => 'nav_my_bricks_by_location',
    'my_bricks_by_type' => 'nav_my_bricks_by_type',
    'my_collection' => 'nav_my_collection',
];
$requestedPage = (string) ($_GET['page'] ?? '');
if ($requestedPage !== '' && isset($stubPages[$requestedPage])) {
    $stubTitle = t($stubPages[$requestedPage]);
    $searchQuery = trim((string) ($_GET['q'] ?? ''));
    $content = '<h1>' . htmlspecialchars($stubTitle) . '</h1>';
    if ($searchQuery !== '') {
        $content .= '<p>' . htmlspecialchars(t('search_results_for', ['query' => $searchQuery])) . '</p>';
    }
    $content .= '<section class="card"><p>' . htmlspecialchars(t('feature_not_implemented')) . '</p></section>';
    renderApp($stubTitle, $content, $user, computeAppStats($pdo));
    exit;
}

$content = '<h1>' . htmlspecialchars(t('welcome_message', ['username' => $user['username']])) . '</h1>';
$content .= '<p>' . htmlspecialchars(t('dashboard_help')) . '</p>';
if ($importMessage !== '') {
    $content .= '<p><strong>' . htmlspecialchars($importMessage) . '</strong></p>';
}
$content .= '<form method="post" enctype="multipart/form-data">'
    . '<input type="hidden" name="action" value="import">'
    . '<label>' . htmlspecialchars(t('import_file_label')) . ' <input type="file" name="import_file" accept=".csv"></label>'
    . '<label>' . htmlspecialchars(t('import_type_label')) . ' <select name="import_type">'
    . '<option value="parts">' . htmlspecialchars(t('import_type_parts')) . '</option>'
    . '<option value="sets">' . htmlspecialchars(t('import_type_sets')) . '</option>'
    . '<option value="set_parts">' . htmlspecialchars(t('import_type_set_parts')) . '</option>'
    . '</select></label>'
    . '<button type="submit">' . htmlspecialchars(t('import_start_button')) . '</button>'
    . '</form>';
$content .= '<p>' . htmlspecialchars(t('import_file_help')) . ' <a href="https://rebrickable.com/downloads/" target="_blank">Rebrickable Downloads</a>.</p>';
renderApp(t('dashboard_title'), $content, $user, computeAppStats($pdo));
