<?php

declare(strict_types=1);

require_once __DIR__ . '/src/db.php';
require_once __DIR__ . '/src/setup.php';
require_once __DIR__ . '/src/import.php';
require_once __DIR__ . '/src/download.php';
require_once __DIR__ . '/src/images.php';
require_once __DIR__ . '/src/storage.php';
require_once __DIR__ . '/src/updater.php';
require_once __DIR__ . '/src/settings.php';
require_once __DIR__ . '/src/i18n.php';
require_once __DIR__ . '/src/icons.php';

// src/config.php is generated by the setup wizard and deliberately not tracked
// in git (see .gitignore) — a fresh install/update copy never has it yet, so
// this must be an existence check, not an unconditional require, or a bare
// clone would fatal-error instead of redirecting to setup.php.
$configPath = __DIR__ . '/src/config.php';
if (!is_file($configPath)) {
    header('Location: setup.php');
    exit;
}
$config = require $configPath;
if (empty($config['db']['dbname']) || empty($config['db']['user']) || !canConnectToServer()) {
    header('Location: setup.php');
    exit;
}

session_start();

try {
    if (!isInstalled()) {
        installDatabase();
        try {
            $result = downloadAndImportRebrickableData();
            $summaryText = implode(', ', array_map(function ($type, $rows) { return "$type=$rows"; }, array_keys($result['summary']), $result['summary']));
            if (!empty($result['errors'])) {
                $errorsText = implode(', ', array_map(function ($type, $msg) { return "$type: $msg"; }, array_keys($result['errors']), $result['errors']));
                $message = t('setup_completed_message_partial', ['summary' => $summaryText, 'errors' => $errorsText]);
            } else {
                $message = t('setup_completed_message_success', ['summary' => $summaryText]);
            }
        } catch (Throwable $e) {
            $message = t('setup_completed_message_error', ['message' => $e->getMessage()]);
        }
        render(t('setup_completed_title'), '<section class="card"><h2>' . htmlspecialchars(t('setup_completed_heading')) . '</h2><p>' . htmlspecialchars($message) . '</p><p>' . htmlspecialchars(t('setup_completed_reload')) . '</p></section>');
        exit;
    }
} catch (Throwable $e) {
    render(t('setup_error_title'), '<section class="card alert"><h2>' . htmlspecialchars(t('setup_error_heading')) . '</h2><p>' . htmlspecialchars(t('setup_error_message', ['message' => $e->getMessage()])) . '</p></section>');
    exit;
}

require_once __DIR__ . '/src/migrations.php';
if (schemaMigrationPending()) {
    try {
        runAllPendingMigrations();
    } catch (Throwable $e) {
        render(t('setup_error_title'), '<section class="card alert"><h2>' . htmlspecialchars(t('setup_error_heading')) . '</h2><p>' . htmlspecialchars(t('setup_error_message', ['message' => $e->getMessage()])) . '</p></section>');
        exit;
    }
}

$pdo = getPDO();

function render(string $title, string $content): void
{
    echo '<!DOCTYPE html><html lang="' . htmlspecialchars(getLocale()) . '"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">';
    echo '<title>' . htmlspecialchars($title) . '</title>';
    echo '<link rel="icon" type="image/svg+xml" href="favicon.svg">';
    echo '<link rel="stylesheet" href="style.css">';
    echo '</head><body>';
    echo '<div class="container">';
    echo '<header><div class="brand"><span class="brand-mark">' . file_get_contents(__DIR__ . '/logo.svg') . '</span><div><h1>' . htmlspecialchars(t('app_title')) . '</h1><small>' . htmlspecialchars(t('app_tagline')) . '</small></div></div></header>';
    echo $content;
    echo '<footer>' . htmlspecialchars(t('app_footer', ['year' => date('Y')])) . '</footer>';
    echo '</div></body></html>';
}

function computeAppStats(PDO $pdo): array
{
    return [
        'bricks_total' => (int) $pdo->query('SELECT COALESCE(SUM(quantity), 0) FROM inventory_parts')->fetchColumn(),
        'bricks_distinct' => (int) $pdo->query('SELECT COUNT(*) FROM parts')->fetchColumn(),
        'sets' => (int) $pdo->query('SELECT COUNT(*) FROM sets')->fetchColumn(),
        'minifigs' => (int) $pdo->query('SELECT COUNT(*) FROM minifigs')->fetchColumn(),
    ];
}

function getNavMenu(): array
{
    return [
        ['icon' => 'build', 'labelKey' => 'nav_build', 'href' => $_SERVER['PHP_SELF'], 'children' => []],
        ['icon' => 'sets', 'labelKey' => 'nav_sets', 'href' => '?page=sets', 'children' => [
            ['labelKey' => 'nav_sets_search', 'href' => '?page=sets_search'],
            ['labelKey' => 'nav_minifigs_search', 'href' => '?page=minifigs_search'],
        ]],
        ['icon' => 'bricks', 'labelKey' => 'nav_bricks', 'href' => '?page=bricks', 'children' => [
            ['labelKey' => 'nav_bricks_search', 'href' => '?page=bricks_search'],
            ['labelKey' => 'nav_colors_search', 'href' => '?page=colors_search'],
        ]],
        ['icon' => 'my_sets', 'labelKey' => 'nav_my_sets', 'href' => '?page=my_sets', 'children' => [
            ['labelKey' => 'nav_my_sets_all', 'href' => '?page=my_sets_all'],
            ['labelKey' => 'nav_my_sets_themes', 'href' => '?page=my_sets_themes'],
        ]],
        ['icon' => 'my_bricks', 'labelKey' => 'nav_my_bricks', 'href' => '?page=my_bricks', 'children' => [
            ['labelKey' => 'nav_my_bricks_all', 'href' => '?page=my_bricks_all'],
            ['labelKey' => 'nav_my_bricks_by_location', 'href' => '?page=my_bricks_by_location'],
            ['labelKey' => 'nav_my_bricks_by_type', 'href' => '?page=my_bricks_by_type'],
        ]],
        ['icon' => 'locations', 'labelKey' => 'locations_title', 'href' => '?page=locations', 'children' => [
            ['labelKey' => 'nav_locations_tree', 'href' => '?page=locations'],
        ]],
        ['icon' => 'collection', 'labelKey' => 'nav_my_collection', 'href' => '?page=my_collection', 'children' => []],
    ];
}

function renderApp(string $title, string $content, array $user, array $stats): void
{
    $locale = getLocale();
    $currentPage = (string) ($_GET['page'] ?? '');

    echo '<!DOCTYPE html><html lang="' . htmlspecialchars($locale) . '"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">';
    echo '<title>' . htmlspecialchars($title) . '</title>';
    echo '<link rel="icon" type="image/svg+xml" href="favicon.svg">';
    echo '<link rel="stylesheet" href="style.css">';
    echo '</head><body>';
    echo '<div class="container">';

    echo '<div class="status-bar">';
    echo '<div class="status-stats">';
    echo '<span class="status-stat"><strong>' . number_format($stats['bricks_total']) . '</strong> ' . htmlspecialchars(t('stat_bricks_total')) . '</span>';
    echo '<span class="status-stat"><strong>' . number_format($stats['bricks_distinct']) . '</strong> ' . htmlspecialchars(t('stat_bricks_distinct')) . '</span>';
    echo '<span class="status-stat"><strong>' . number_format($stats['sets']) . '</strong> ' . htmlspecialchars(t('stat_sets')) . '</span>';
    echo '<span class="status-stat"><strong>' . number_format($stats['minifigs']) . '</strong> ' . htmlspecialchars(t('stat_minifigs')) . '</span>';
    echo '</div>';
    echo '<div class="status-user">';
    echo '<a class="status-username" href="?page=settings">' . htmlspecialchars($user['username']) . '</a>';
    echo '<a class="status-icon-link" href="?page=settings" title="' . htmlspecialchars(t('settings_title')) . '">' . getNavIcon('settings') . '</a>';
    echo '<a class="status-icon-link" href="?action=logout" title="' . htmlspecialchars(t('logout')) . '">' . getNavIcon('logout') . '</a>';
    echo '<span class="lang-flags">';
    foreach (['de' => '🇩🇪', 'en' => '🇬🇧'] as $flagLocale => $flagEmoji) {
        $activeClass = $flagLocale === $locale ? ' active' : '';
        $redirectPage = $currentPage !== '' ? '&page=' . urlencode($currentPage) : '';
        $flagHref = htmlspecialchars('?action=set_locale&locale=' . $flagLocale . $redirectPage);
        echo '<a class="lang-flag' . $activeClass . '" href="' . $flagHref . '" title="' . htmlspecialchars(getLocaleLabel($flagLocale)) . '">' . $flagEmoji . '</a>';
    }
    echo '</span>';
    echo '</div>';
    echo '</div>';

    echo '<header class="main-nav">';
    echo '<a class="logo-link" href="' . htmlspecialchars($_SERVER['PHP_SELF']) . '"><span class="logo-mark">' . file_get_contents(__DIR__ . '/logo.svg') . '</span></a>';
    echo '<nav class="nav-list">';
    foreach (getNavMenu() as $item) {
        echo '<div class="nav-item">';
        echo '<a class="nav-link" href="' . htmlspecialchars($item['href']) . '"><span class="nav-icon">' . getNavIcon($item['icon']) . '</span><span class="nav-label">' . htmlspecialchars(t($item['labelKey'])) . '</span></a>';
        if (!empty($item['children'])) {
            echo '<div class="nav-dropdown">';
            foreach ($item['children'] as $child) {
                echo '<a href="' . htmlspecialchars($child['href']) . '">' . htmlspecialchars(t($child['labelKey'])) . '</a>';
            }
            echo '</div>';
        }
        echo '</div>';
    }
    echo '</nav>';
    echo '</header>';

    echo '<main>' . $content . '</main>';
    echo '<footer>' . htmlspecialchars(t('app_footer', ['year' => date('Y')])) . '</footer>';
    echo '</div></body></html>';
}

if (isset($_POST['action']) && $_POST['action'] === 'register') {
    $username = trim($_POST['username'] ?? '');
    $password = $_POST['password'] ?? '';
    $email = trim($_POST['email'] ?? '');

    if ($username !== '' && $password !== '') {
        $hash = password_hash($password, PASSWORD_DEFAULT);
        $stmt = $pdo->prepare('INSERT INTO users (username, password_hash, email) VALUES (?, ?, ?)');
        $stmt->execute([$username, $hash, $email]);
        render(t('register_success_title'), '<section class="card notice"><h2>' . htmlspecialchars(t('register_success_heading')) . '</h2><p>' . htmlspecialchars(t('register_success_message')) . '</p></section>');
        exit;
    }
}

if (isset($_POST['action']) && $_POST['action'] === 'login') {
    $username = trim($_POST['username'] ?? '');
    $password = $_POST['password'] ?? '';
    $stmt = $pdo->prepare('SELECT id, password_hash FROM users WHERE username = ?');
    $stmt->execute([$username]);
    $user = $stmt->fetch();
    if ($user && password_verify($password, $user['password_hash'])) {
        $_SESSION['user_id'] = $user['id'];
        header('Location: ' . $_SERVER['PHP_SELF']);
        exit;
    }
    render(t('login_failed_title'), '<section class="card alert"><h2>' . htmlspecialchars(t('login_failed_heading')) . '</h2><p>' . htmlspecialchars(t('login_failed_message')) . '</p></section>');
    exit;
}

$importMessage = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'import') {
    try {
        $type = $_POST['import_type'] ?? '';
        if (!isset($_FILES['import_file']) || $_FILES['import_file']['error'] !== UPLOAD_ERR_OK) {
            throw new RuntimeException(t('error_import_file_required'));
        }
        $result = importCsv($_FILES['import_file']['tmp_name'], $type);
        $importMessage = t('import_success_rows', ['count' => $result['rows'] ?? 0]);
    } catch (Throwable $e) {
        $importMessage = t('import_failure_message', ['message' => $e->getMessage()]);
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'update_data') {
    try {
        $result = downloadAndImportRebrickableData();
        $summaryText = implode(', ', array_map(function ($type, $rows) { return "$type=$rows"; }, array_keys($result['summary']), $result['summary']));
        if (!empty($result['errors'])) {
            $errorsText = implode(', ', array_map(function ($type, $msg) { return "$type: $msg"; }, array_keys($result['errors']), $result['errors']));
            $importMessage = t('update_partial_message', ['summary' => $summaryText, 'errors' => $errorsText]);
        } else {
            $importMessage = t('update_success_message', ['summary' => $summaryText]);
        }
    } catch (Throwable $e) {
        $importMessage = t('update_failure_message', ['message' => $e->getMessage()]);
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'update_rebrickable_settings') {
    setAppSetting('rebrickable_download_base_url', trim($_POST['download_base_url'] ?? ''));
    setAppSetting('rebrickable_api_url', trim($_POST['api_url'] ?? ''));
    setAppSetting('rebrickable_api_key', trim($_POST['api_key'] ?? ''));
    $importMessage = t('settings_rebrickable_saved');
}

if (isset($_GET['action']) && $_GET['action'] === 'logout') {
    session_destroy();
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
}

if (isset($_GET['action']) && $_GET['action'] === 'set_locale') {
    setSessionLocale((string) ($_GET['locale'] ?? ''));
    $redirectPage = isset($_GET['page']) ? '?page=' . urlencode((string) $_GET['page']) : '';
    header('Location: ' . $_SERVER['PHP_SELF'] . $redirectPage);
    exit;
}

if (!isset($_SESSION['user_id'])) {
    $content = '<section class="card"><h2>' . htmlspecialchars(t('login_title')) . '</h2><form method="post"><input type="hidden" name="action" value="login"><label>' . htmlspecialchars(t('login_username')) . '<input name="username" autocomplete="username"></label><label>' . htmlspecialchars(t('login_password')) . '<input type="password" name="password" autocomplete="current-password"></label><button type="submit">' . htmlspecialchars(t('login_button')) . '</button></form></section>';
    $content .= '<section class="card"><h2>' . htmlspecialchars(t('register_title')) . '</h2><form method="post"><input type="hidden" name="action" value="register"><label>' . htmlspecialchars(t('register_username')) . '<input name="username" autocomplete="username"></label><label>' . htmlspecialchars(t('register_email')) . '<input type="email" name="email" autocomplete="email"></label><label>' . htmlspecialchars(t('register_password')) . '<input type="password" name="password" autocomplete="new-password"></label><button type="submit">' . htmlspecialchars(t('register_button')) . '</button></form></section>';
    render(t('login_register_title'), $content);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'image_tick') {
    header('Content-Type: application/json');
    try {
        $state = $_SESSION['image_download_state'] ?? null;
        if (!is_array($state)) {
            $forceRefresh = ($_POST['force_refresh'] ?? '') === '1';
            $state = initImageDownloadState($forceRefresh);
        }

        $result = stepImageDownload($state);
        $_SESSION['image_download_state'] = $state;

        $payload = buildImageProgressPayload($state, $result['done']);

        if ($result['done']) {
            unset($_SESSION['image_download_state']);
        }

        echo json_encode($payload, JSON_UNESCAPED_UNICODE);
    } catch (Throwable $e) {
        http_response_code(500);
        echo json_encode([
            'status' => 'error',
            'percent' => 0,
            'message' => t('import_error', ['message' => $e->getMessage()]),
            'tables' => [],
        ], JSON_UNESCAPED_UNICODE);
    }
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'check_update') {
    header('Content-Type: application/json');
    try {
        $release = isUpdateAvailable();
        if ($release !== null) {
            $_SESSION['update_available_release'] = $release;
        } else {
            unset($_SESSION['update_available_release']);
        }
        echo json_encode([
            'available' => $release !== null,
            'release' => $release,
            'currentVersion' => getCurrentVersion(),
        ], JSON_UNESCAPED_UNICODE);
    } catch (Throwable $e) {
        http_response_code(500);
        echo json_encode(['available' => false, 'error' => $e->getMessage()], JSON_UNESCAPED_UNICODE);
    }
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'update_tick') {
    header('Content-Type: application/json');
    try {
        $state = $_SESSION['update_state'] ?? null;
        if (!is_array($state)) {
            $release = $_SESSION['update_available_release'] ?? null;
            if ($release === null) {
                throw new RuntimeException(t('update_no_release_selected'));
            }
            $state = initUpdateState($release);
        }

        $result = stepUpdate($state);
        $_SESSION['update_state'] = $state;

        $payload = buildUpdateProgressPayload($state, $result['done']);

        if ($result['done']) {
            unset($_SESSION['update_state'], $_SESSION['update_available_release']);
        }

        echo json_encode($payload, JSON_UNESCAPED_UNICODE);
    } catch (Throwable $e) {
        unset($_SESSION['update_state']);
        http_response_code(500);
        echo json_encode([
            'status' => 'error',
            'percent' => 0,
            'message' => t('update_failed', ['message' => $e->getMessage()]),
        ], JSON_UNESCAPED_UNICODE);
    }
    exit;
}

$locationMessage = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'add_location') {
    $name = trim($_POST['name'] ?? '');
    $type = trim($_POST['type'] ?? '');
    $type = isValidLocationType($type) ? $type : null;
    $parentId = trim($_POST['parent_id'] ?? '') !== '' ? (int) $_POST['parent_id'] : null;
    $childCount = (int) ($_POST['child_count'] ?? 0);
    $namingPattern = trim($_POST['naming_pattern'] ?? '');

    if ($name === '') {
        $locationMessage = t('location_name_required');
    } else {
        try {
            $types = getLocationTypes();
            $supportsBulk = $type !== null && $types[$type]['bulkChildKey'] !== null;
            if ($supportsBulk && $childCount > 0 && $namingPattern !== '') {
                createStorageLocationWithChildren($parentId, $name, $type, $childCount, $namingPattern);
            } else {
                createStorageLocation($parentId, $name, $type);
            }
            $locationMessage = t('location_added_message', ['name' => $name]);
        } catch (Throwable $e) {
            $locationMessage = t('location_save_failed', ['message' => $e->getMessage()]);
        }
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'rename_location') {
    $locationId = (int) ($_POST['location_id'] ?? 0);
    $name = trim($_POST['name'] ?? '');
    $type = trim($_POST['type'] ?? '');
    $type = isValidLocationType($type) ? $type : null;

    if ($name === '') {
        $locationMessage = t('location_name_required');
    } else {
        try {
            renameStorageLocation($locationId, $name, $type);
            $locationMessage = t('location_updated_message');
        } catch (Throwable $e) {
            $locationMessage = t('location_save_failed', ['message' => $e->getMessage()]);
        }
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'delete_location') {
    $locationId = (int) ($_POST['location_id'] ?? 0);
    if (locationHasChildren($locationId)) {
        $locationMessage = t('location_delete_blocked_children');
    } elseif (locationHasStock($locationId)) {
        $locationMessage = t('location_delete_blocked_stock');
    } else {
        try {
            deleteStorageLocation($locationId);
            $locationMessage = t('location_deleted_message');
        } catch (Throwable $e) {
            $locationMessage = t('location_save_failed', ['message' => $e->getMessage()]);
        }
    }
}

$stmt = $pdo->prepare('SELECT username FROM users WHERE id = ?');
$stmt->execute([$_SESSION['user_id']]);
$user = $stmt->fetch();

if ($user === false) {
    session_destroy();
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
}

if (isset($_GET['page']) && $_GET['page'] === 'settings') {
    $content = '<h1>' . htmlspecialchars(t('settings_title')) . '</h1>';
    $content .= '<p><a href="' . $_SERVER['PHP_SELF'] . '">' . htmlspecialchars(t('settings_back')) . '</a></p>';
    if ($importMessage !== '') {
        $content .= '<p><strong>' . htmlspecialchars($importMessage) . '</strong></p>';
    }
    $content .= '<form method="post"><input type="hidden" name="action" value="update_data"><button type="submit">' . htmlspecialchars(t('settings_update_button')) . '</button></form>';
    $content .= '<p>' . htmlspecialchars(t('settings_update_help')) . '</p>';
    $content .= '<h2>' . htmlspecialchars(t('settings_recent_updates')) . '</h2>';
    $content .= '<ul>';
    $content .= '<li>' . htmlspecialchars(t('settings_last_update_all', ['value' => getAppSetting('last_update_all', t('not_available'))])) . '</li>';
    $content .= '<li>' . htmlspecialchars(t('settings_last_update_parts', ['value' => getAppSetting('last_update_parts', t('not_available'))])) . '</li>';
    $content .= '<li>' . htmlspecialchars(t('settings_last_update_sets', ['value' => getAppSetting('last_update_sets', t('not_available'))])) . '</li>';
    $content .= '<li>' . htmlspecialchars(t('settings_last_update_set_parts', ['value' => getAppSetting('last_update_set_parts', t('not_available'))])) . '</li>';
    $content .= '</ul>';

    $content .= '<h2>' . htmlspecialchars(t('settings_rebrickable_title')) . '</h2>';
    $content .= '<p>' . htmlspecialchars(t('settings_rebrickable_help')) . '</p>';
    $content .= '<form method="post">';
    $content .= '<input type="hidden" name="action" value="update_rebrickable_settings">';
    $content .= '<label>' . htmlspecialchars(t('settings_download_base_url_label'))
        . '<input name="download_base_url" value="' . htmlspecialchars((string) getAppSetting('rebrickable_download_base_url', '')) . '" placeholder="https://cdn.rebrickable.com/media/downloads/"></label>';
    $content .= '<small>' . htmlspecialchars(t('settings_download_base_url_help')) . '</small>';
    $content .= '<label>' . htmlspecialchars(t('settings_api_url_label'))
        . '<input name="api_url" value="' . htmlspecialchars((string) getAppSetting('rebrickable_api_url', '')) . '" placeholder="https://rebrickable.com/api/v3/"></label>';
    $content .= '<small>' . htmlspecialchars(t('settings_api_url_help')) . '</small>';
    $content .= '<label>' . htmlspecialchars(t('settings_api_key_label'))
        . '<input name="api_key" value="' . htmlspecialchars((string) getAppSetting('rebrickable_api_key', '')) . '"></label>';
    $content .= '<button type="submit">' . htmlspecialchars(t('settings_rebrickable_save_button')) . '</button>';
    $content .= '</form>';

    $content .= '<h2>' . htmlspecialchars(t('image_download')) . '</h2>';
    $content .= '<p>' . htmlspecialchars(t('image_download_help')) . '</p>';
    $content .= '<form method="post" id="image-form">';
    $content .= '<label class="checkbox-label"><input type="checkbox" name="force_refresh" value="1"> ' . htmlspecialchars(t('image_force_refresh_label')) . '</label>';
    $content .= '<p class="hint">' . htmlspecialchars(t('image_force_refresh_help')) . '</p>';
    $content .= '<div class="import-status" id="imageStatus">';
    $content .= '<div class="progress-message idle" id="imageMessage">' . htmlspecialchars(t('import_not_started')) . '</div>';
    $content .= '<div class="progress-track" id="imageProgress"><div class="progress-fill"></div></div>';
    $content .= '<ul class="import-file-list" id="imageTableList">';
    $imageTables = [
        'sets' => t('image_table_sets'),
        'minifigs' => t('image_table_minifigs'),
        'inventory_parts' => t('image_table_inventory_parts'),
    ];
    foreach ($imageTables as $tableKey => $tableLabel) {
        $content .= '<li class="import-file import-file-pending" data-table="' . htmlspecialchars($tableKey) . '"><span class="import-file-name">' . htmlspecialchars($tableLabel) . '</span><span class="import-file-status">' . htmlspecialchars(t('import_stage_pending')) . '</span></li>';
    }
    $content .= '</ul>';
    $content .= '</div>';
    $content .= '<button type="submit">' . htmlspecialchars(t('image_download_button')) . '</button>';
    $content .= '</form>';
    $imageLabelsJson = json_encode([
        'running' => t('image_download_running'),
        'button' => t('image_download_button'),
        'resume_button' => t('import_resume_button'),
        'error_retry' => t('import_error_retry'),
        'started' => t('import_started'),
        'stage_pending' => t('import_stage_pending'),
        'stage_running' => t('image_stage_running'),
        'stage_done' => t('import_stage_done'),
        'processed_of_total' => t('image_processed_of_total'),
        'downloaded_label' => t('image_downloaded_label'),
        'skipped_label' => t('image_skipped_label'),
        'errors_label' => t('image_errors_label'),
    ], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT);
    $content .= <<<SCRIPT
<script>
(function(){
  var texts = $imageLabelsJson;
  var stageLabels = {
    pending: texts.stage_pending,
    running: texts.stage_running,
    done: texts.stage_done
  };
  var form = document.getElementById("image-form");
  var track = document.getElementById("imageProgress");
  var fill = track ? track.querySelector(".progress-fill") : null;
  var msg = document.getElementById("imageMessage");
  var tableList = document.getElementById("imageTableList");
  if (!form || !track || !fill || !msg || !tableList) {
    return;
  }

  function formatNumber(n) {
    if (n === null || n === undefined) {
      return "0";
    }
    return String(n).replace(/\\B(?=(\\d{3})+(?!\\d))/g, ".");
  }

  function renderTables(tables) {
    tableList.innerHTML = "";
    Object.keys(tables).forEach(function(key) {
      var table = tables[key];
      var li = document.createElement("li");
      li.className = "import-file import-file-" + (table.stage === "done" ? "done" : (table.stage === "running" ? "importing" : "pending"));

      var name = document.createElement("span");
      name.className = "import-file-name";
      name.textContent = key;

      var status = document.createElement("span");
      status.className = "import-file-status";
      var text = stageLabels[table.stage] || table.stage;
      if (table.stage !== "pending") {
        text += " — " + texts.processed_of_total
          .replace("{processed}", formatNumber(table.processed))
          .replace("{total}", formatNumber(table.total));
        text += " (" + texts.downloaded_label + ": " + formatNumber(table.downloaded)
          + ", " + texts.skipped_label + ": " + formatNumber(table.skipped)
          + ", " + texts.errors_label + ": " + formatNumber(table.errors) + ")";
      }
      status.textContent = text;

      li.appendChild(name);
      li.appendChild(status);
      tableList.appendChild(li);
    });
  }

  function updateStatus(data) {
    msg.classList.remove("idle");
    msg.textContent = data.message || texts.running;
    fill.style.width = (data.percent || 0) + "%";
    if (data.tables) {
      renderTables(data.tables);
    }
  }

  async function tick(formData) {
    var response = await fetch('?page=settings', {
      method: 'POST',
      body: formData,
      credentials: 'same-origin'
    });
    if (!response.ok && response.status !== 500) {
      throw new Error('tick failed with status ' + response.status);
    }
    return await response.json();
  }

  var hasStarted = false;
  var consecutiveFailures = 0;
  var maxAutoRetries = 4;

  form.addEventListener("submit", function(event) {
    event.preventDefault();
    var submitButton = form.querySelector("button[type=submit]");
    if (submitButton) {
      submitButton.disabled = true;
      submitButton.textContent = texts.running;
    }

    if (!hasStarted) {
      updateStatus({percent: 0, message: texts.started, tables: {}});
      hasStarted = true;
    } else if (msg) {
      msg.textContent = texts.running;
    }

    var baseFormData = new FormData(form);
    baseFormData.set('action', 'image_tick');
    if (!form.querySelector('input[name=force_refresh]').checked) {
      baseFormData.delete('force_refresh');
    }

    function pauseWithMessage(message) {
      if (submitButton) {
        submitButton.disabled = false;
        submitButton.textContent = texts.resume_button;
      }
      if (msg) {
        msg.textContent = message || texts.error_retry;
      }
    }

    function loop() {
      tick(baseFormData).then(function(data) {
        consecutiveFailures = 0;
        updateStatus(data);
        if (data.status === 'done') {
          if (submitButton) {
            submitButton.disabled = false;
            submitButton.textContent = texts.button;
          }
          return;
        }
        if (data.status === 'error') {
          pauseWithMessage(data.message);
          return;
        }
        setTimeout(loop, 50);
      }).catch(function() {
        consecutiveFailures++;
        if (consecutiveFailures <= maxAutoRetries) {
          if (msg) {
            msg.textContent = texts.error_retry + ' (' + consecutiveFailures + '/' + maxAutoRetries + ')';
          }
          setTimeout(loop, 1000 * consecutiveFailures);
          return;
        }
        pauseWithMessage(texts.error_retry);
      });
    }

    loop();
  });
})();
</script>
SCRIPT;

    $content .= '<h2>' . htmlspecialchars(t('update_title')) . '</h2>';
    $content .= '<p>' . htmlspecialchars(t('update_current_version', ['version' => getCurrentVersion()])) . '</p>';
    $content .= '<p class="hint">' . htmlspecialchars(t('update_warning')) . '</p>';
    $content .= '<button type="button" id="update-check-button">' . htmlspecialchars(t('update_check_button')) . '</button>';
    $content .= '<div id="update-info" style="display:none; margin-top: 1rem;"></div>';
    $content .= '<div class="import-status" id="updateStatus" style="display:none;">';
    $content .= '<div class="progress-message" id="updateMessage"></div>';
    $content .= '<div class="progress-track" id="updateProgress"><div class="progress-fill"></div></div>';
    $content .= '</div>';
    $content .= '<button type="button" id="update-apply-button" style="display:none; margin-top: 1rem;">' . htmlspecialchars(t('update_apply_button')) . '</button>';
    $updateLabelsJson = json_encode([
        'checking' => t('update_checking'),
        'checkButton' => t('update_check_button'),
        'upToDate' => t('update_up_to_date'),
        'checkFailed' => t('update_check_failed'),
        'available' => t('update_available'),
        'applyButton' => t('update_apply_button'),
        'running' => t('update_running'),
        'errorRetry' => t('import_error_retry'),
        'resumeButton' => t('import_resume_button'),
        'stageDownloading' => t('update_stage_downloading'),
        'stageExtracting' => t('update_stage_extracting'),
        'stageDiffing' => t('update_stage_diffing'),
        'stageCopying' => t('update_stage_copying'),
        'stageDeleting' => t('update_stage_deleting'),
        'stageMigrating' => t('update_stage_migrating'),
        'stageDone' => t('update_stage_done'),
        'reloadNotice' => t('update_reload_notice'),
    ], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT);
    $content .= <<<SCRIPT
<script>
(function(){
  var texts = $updateLabelsJson;
  var checkButton = document.getElementById("update-check-button");
  var infoBox = document.getElementById("update-info");
  var applyButton = document.getElementById("update-apply-button");
  var statusWrap = document.getElementById("updateStatus");
  var msg = document.getElementById("updateMessage");
  var track = document.getElementById("updateProgress");
  var fill = track ? track.querySelector(".progress-fill") : null;
  if (!checkButton || !infoBox || !applyButton || !statusWrap || !msg || !fill) {
    return;
  }

  function stageText(data) {
    switch (data.stage) {
      case "downloading":
        return texts.stageDownloading;
      case "extracting":
        return texts.stageExtracting;
      case "diffing":
        return texts.stageDiffing;
      case "copying":
        return texts.stageCopying + " (" + data.filesToCopyDone + "/" + data.filesToCopyTotal + ")";
      case "deleting":
        return texts.stageDeleting + " (" + data.filesToDeleteDone + "/" + data.filesToDeleteTotal + ")";
      case "migrating":
        return texts.stageMigrating;
      case "done":
        return texts.stageDone;
      default:
        return texts.running;
    }
  }

  checkButton.addEventListener("click", function() {
    checkButton.disabled = true;
    checkButton.textContent = texts.checking;
    infoBox.style.display = "none";

    var formData = new FormData();
    formData.set("action", "check_update");

    fetch("?page=settings", { method: "POST", body: formData, credentials: "same-origin" })
      .then(function(r) { return r.json(); })
      .then(function(data) {
        checkButton.disabled = false;
        checkButton.textContent = texts.checkButton;
        infoBox.style.display = "block";
        if (data.available && data.release) {
          infoBox.textContent = texts.available.replace("{version}", data.release.version);
          applyButton.style.display = "inline-block";
        } else if (data.error) {
          infoBox.textContent = texts.checkFailed;
          applyButton.style.display = "none";
        } else {
          infoBox.textContent = texts.upToDate;
          applyButton.style.display = "none";
        }
      })
      .catch(function() {
        checkButton.disabled = false;
        checkButton.textContent = texts.checkButton;
        infoBox.style.display = "block";
        infoBox.textContent = texts.checkFailed;
      });
  });

  var consecutiveFailures = 0;
  var maxAutoRetries = 4;

  applyButton.addEventListener("click", function() {
    applyButton.disabled = true;
    applyButton.textContent = texts.running;
    statusWrap.style.display = "block";
    msg.textContent = texts.running;
    fill.style.width = "0%";

    var formData = new FormData();
    formData.set("action", "update_tick");

    function pauseWithMessage(message) {
      applyButton.disabled = false;
      applyButton.textContent = texts.resumeButton;
      msg.textContent = message || texts.errorRetry;
    }

    function loop() {
      fetch("?page=settings", { method: "POST", body: formData, credentials: "same-origin" })
        .then(function(r) {
          if (!r.ok && r.status !== 500) {
            throw new Error("tick failed with status " + r.status);
          }
          return r.json();
        })
        .then(function(data) {
          consecutiveFailures = 0;
          if (data.status === "error") {
            pauseWithMessage(data.message);
            return;
          }
          fill.style.width = (data.percent || 0) + "%";
          msg.textContent = stageText(data);
          if (data.status === "done") {
            msg.textContent = texts.reloadNotice;
            setTimeout(function() { window.location.reload(); }, 800);
            return;
          }
          setTimeout(loop, 50);
        })
        .catch(function() {
          consecutiveFailures++;
          if (consecutiveFailures <= maxAutoRetries) {
            msg.textContent = texts.errorRetry + " (" + consecutiveFailures + "/" + maxAutoRetries + ")";
            setTimeout(loop, 1000 * consecutiveFailures);
            return;
          }
          pauseWithMessage(texts.errorRetry);
        });
    }

    loop();
  });
})();
</script>
SCRIPT;

    renderApp(t('settings_title'), $content, $user, computeAppStats($pdo));
    exit;
}

if (isset($_GET['page']) && $_GET['page'] === 'locations') {
    $editId = isset($_GET['edit']) ? (int) $_GET['edit'] : null;
    $editLocation = $editId !== null ? getStorageLocation($editId) : null;

    $content = '<h1>' . htmlspecialchars(t('locations_title')) . '</h1>';
    $content .= '<p><a href="' . $_SERVER['PHP_SELF'] . '">' . htmlspecialchars(t('settings_back')) . '</a></p>';
    $content .= '<p>' . htmlspecialchars(t('locations_help')) . '</p>';
    if ($locationMessage !== '') {
        $content .= '<p><strong>' . htmlspecialchars($locationMessage) . '</strong></p>';
    }

    $locationOptions = getStorageLocationOptions();
    $types = getLocationTypes();
    $isEdit = $editLocation !== null;

    $content .= '<section class="card"><h2>' . htmlspecialchars($isEdit ? t('location_edit_title') : t('location_add_title')) . '</h2>';
    $content .= '<form method="post" id="location-form">';
    if ($isEdit) {
        $content .= '<input type="hidden" name="action" value="rename_location">';
        $content .= '<input type="hidden" name="location_id" value="' . (int) $editLocation['id'] . '">';
    } else {
        $content .= '<input type="hidden" name="action" value="add_location">';
        $content .= '<label>' . htmlspecialchars(t('location_parent_label')) . '<select name="parent_id">';
        $content .= '<option value="">' . htmlspecialchars(t('location_parent_none')) . '</option>';
        foreach ($locationOptions as $optId => $optLabel) {
            $content .= '<option value="' . $optId . '">' . htmlspecialchars($optLabel) . '</option>';
        }
        $content .= '</select></label>';
    }
    $content .= '<label>' . htmlspecialchars(t('location_name_label')) . '<input name="name" value="' . htmlspecialchars($isEdit ? $editLocation['name'] : '') . '" required></label>';
    $content .= '<label>' . htmlspecialchars(t('location_type_label')) . '<select name="type" id="location-type-select">';
    $content .= '<option value="">' . htmlspecialchars(t('location_type_none')) . '</option>';
    $currentType = $isEdit ? $editLocation['location_type'] : null;
    foreach ($types as $typeKey => $typeConfig) {
        $selected = $typeKey === $currentType ? ' selected' : '';
        $content .= '<option value="' . htmlspecialchars($typeKey) . '"' . $selected . '>' . htmlspecialchars(t($typeConfig['labelKey'])) . '</option>';
    }
    $content .= '</select></label>';

    if (!$isEdit) {
        $content .= '<div id="location-bulk-fields" style="display:none;">';
        $content .= '<label>' . htmlspecialchars(t('location_bulk_count_label')) . '<input type="number" name="child_count" min="0" value="0"></label>';
        $content .= '<label>' . htmlspecialchars(t('location_bulk_naming_label')) . '<input type="text" name="naming_pattern" id="location-naming-pattern" value=""></label>';
        $content .= '</div>';
    }

    $content .= '<button type="submit">' . htmlspecialchars($isEdit ? t('location_save_button') : t('location_add_button')) . '</button>';
    if ($isEdit) {
        $content .= ' <a href="?page=locations">' . htmlspecialchars(t('location_cancel_edit')) . '</a>';
    }
    $content .= '</form></section>';

    if (!$isEdit) {
        $bulkPatterns = [];
        foreach ($types as $typeKey => $typeConfig) {
            $bulkPatterns[$typeKey] = $typeConfig['bulkChildKey'] !== null ? t($typeConfig['bulkChildKey']) : null;
        }
        $bulkPatternsJson = json_encode($bulkPatterns, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT);
        $content .= <<<SCRIPT
<script>
(function(){
  var patterns = $bulkPatternsJson;
  var typeSelect = document.getElementById("location-type-select");
  var bulkFields = document.getElementById("location-bulk-fields");
  var namingInput = document.getElementById("location-naming-pattern");
  if (!typeSelect || !bulkFields || !namingInput) {
    return;
  }
  function update() {
    var pattern = patterns[typeSelect.value];
    if (pattern) {
      bulkFields.style.display = "block";
      namingInput.value = pattern;
    } else {
      bulkFields.style.display = "none";
      namingInput.value = "";
    }
  }
  typeSelect.addEventListener("change", update);
  update();
})();
</script>
SCRIPT;
    }

    $content .= '<section class="card"><h2>' . htmlspecialchars(t('locations_tree_title')) . '</h2>';
    $tree = getStorageLocationTree();
    if (empty($tree)) {
        $content .= '<p>' . htmlspecialchars(t('locations_tree_empty')) . '</p>';
    } else {
        $renderNode = function (array $nodes) use (&$renderNode, $types): string {
            $html = '<ul class="location-tree">';
            foreach ($nodes as $node) {
                $typeLabel = $node['location_type'] !== null && isset($types[$node['location_type']])
                    ? t($types[$node['location_type']]['labelKey'])
                    : '';
                $html .= '<li>';
                $html .= '<span class="location-name">' . htmlspecialchars($node['name']) . '</span>';
                if ($typeLabel !== '') {
                    $html .= ' <span class="location-type-badge">' . htmlspecialchars($typeLabel) . '</span>';
                }
                $html .= ' <a href="?page=locations&edit=' . (int) $node['id'] . '">' . htmlspecialchars(t('location_edit_link')) . '</a>';
                $html .= ' <form method="post" class="location-delete-form"><input type="hidden" name="action" value="delete_location"><input type="hidden" name="location_id" value="' . (int) $node['id'] . '"><button type="submit" class="link-button">' . htmlspecialchars(t('location_delete_link')) . '</button></form>';
                if (!empty($node['children'])) {
                    $html .= $renderNode($node['children']);
                }
                $html .= '</li>';
            }
            $html .= '</ul>';
            return $html;
        };
        $content .= $renderNode($tree);
    }
    $content .= '</section>';

    renderApp(t('locations_title'), $content, $user, computeAppStats($pdo));
    exit;
}

$stubPages = [
    'sets' => 'nav_sets',
    'sets_search' => 'nav_sets_search',
    'minifigs_search' => 'nav_minifigs_search',
    'bricks' => 'nav_bricks',
    'bricks_search' => 'nav_bricks_search',
    'colors_search' => 'nav_colors_search',
    'my_sets' => 'nav_my_sets',
    'my_sets_all' => 'nav_my_sets_all',
    'my_sets_themes' => 'nav_my_sets_themes',
    'my_bricks' => 'nav_my_bricks',
    'my_bricks_all' => 'nav_my_bricks_all',
    'my_bricks_by_location' => 'nav_my_bricks_by_location',
    'my_bricks_by_type' => 'nav_my_bricks_by_type',
    'my_collection' => 'nav_my_collection',
];
$requestedPage = (string) ($_GET['page'] ?? '');
if ($requestedPage !== '' && isset($stubPages[$requestedPage])) {
    $stubTitle = t($stubPages[$requestedPage]);
    $content = '<h1>' . htmlspecialchars($stubTitle) . '</h1>';
    $content .= '<section class="card"><p>' . htmlspecialchars(t('feature_not_implemented')) . '</p></section>';
    renderApp($stubTitle, $content, $user, computeAppStats($pdo));
    exit;
}

$content = '<h1>' . htmlspecialchars(t('welcome_message', ['username' => $user['username']])) . '</h1>';
$content .= '<p>' . htmlspecialchars(t('dashboard_help')) . '</p>';
if ($importMessage !== '') {
    $content .= '<p><strong>' . htmlspecialchars($importMessage) . '</strong></p>';
}
$content .= '<form method="post" enctype="multipart/form-data">'
    . '<input type="hidden" name="action" value="import">'
    . '<label>' . htmlspecialchars(t('import_file_label')) . ' <input type="file" name="import_file" accept=".csv"></label>'
    . '<label>' . htmlspecialchars(t('import_type_label')) . ' <select name="import_type">'
    . '<option value="parts">' . htmlspecialchars(t('import_type_parts')) . '</option>'
    . '<option value="sets">' . htmlspecialchars(t('import_type_sets')) . '</option>'
    . '<option value="set_parts">' . htmlspecialchars(t('import_type_set_parts')) . '</option>'
    . '</select></label>'
    . '<button type="submit">' . htmlspecialchars(t('import_start_button')) . '</button>'
    . '</form>';
$content .= '<p>' . htmlspecialchars(t('import_file_help')) . ' <a href="https://rebrickable.com/downloads/" target="_blank">Rebrickable Downloads</a>.</p>';
renderApp(t('dashboard_title'), $content, $user, computeAppStats($pdo));
