<?php

declare(strict_types=1);

require_once __DIR__ . '/src/db.php';
require_once __DIR__ . '/src/setup.php';
require_once __DIR__ . '/src/import.php';
require_once __DIR__ . '/src/download.php';
require_once __DIR__ . '/src/images.php';
require_once __DIR__ . '/src/storage.php';
require_once __DIR__ . '/src/updater.php';
require_once __DIR__ . '/src/settings.php';
require_once __DIR__ . '/src/i18n.php';
require_once __DIR__ . '/src/icons.php';
require_once __DIR__ . '/src/parts.php';
require_once __DIR__ . '/src/part_modal.php';
require_once __DIR__ . '/src/part_images.php';
require_once __DIR__ . '/src/sets.php';
require_once __DIR__ . '/src/instructions.php';
require_once __DIR__ . '/src/ldraw.php';
require_once __DIR__ . '/src/owned_sets.php';
require_once __DIR__ . '/src/owned_set_wizard.php';
require_once __DIR__ . '/src/minifigs.php';
require_once __DIR__ . '/src/stats.php';
require_once __DIR__ . '/src/dashboard.php';

// src/config.php is generated by the setup wizard and deliberately not tracked
// in git (see .gitignore) — a fresh install/update copy never has it yet, so
// this must be an existence check, not an unconditional require, or a bare
// clone would fatal-error instead of redirecting to setup.php.
$configPath = __DIR__ . '/src/config.php';
if (!is_file($configPath)) {
    header('Location: setup.php');
    exit;
}
$config = require $configPath;
if (empty($config['db']['dbname']) || empty($config['db']['user']) || !canConnectToServer()) {
    header('Location: setup.php');
    exit;
}

// A login should stay valid for 12 months — both the cookie the browser
// holds onto and, since PHP's own garbage collection would otherwise still
// be free to delete the session data much sooner (default ~24 min of
// inactivity), the server-side session lifetime too. Only 'lifetime' is
// passed to session_set_cookie_params() so every other cookie attribute
// (path, domain, secure, httponly, samesite) keeps using the host's own
// ini defaults rather than this app overriding them.
const LOGIN_SESSION_LIFETIME_SECONDS = 60 * 60 * 24 * 365;
session_set_cookie_params(['lifetime' => LOGIN_SESSION_LIFETIME_SECONDS]);
ini_set('session.gc_maxlifetime', (string) LOGIN_SESSION_LIFETIME_SECONDS);
session_start();

try {
    if (!isInstalled()) {
        installDatabase();
        try {
            $result = downloadAndImportRebrickableData();
            $summaryText = implode(', ', array_map(function ($type, $rows) { return "$type=$rows"; }, array_keys($result['summary']), $result['summary']));
            if (!empty($result['errors'])) {
                $errorsText = implode(', ', array_map(function ($type, $msg) { return "$type: $msg"; }, array_keys($result['errors']), $result['errors']));
                $message = t('setup_completed_message_partial', ['summary' => $summaryText, 'errors' => $errorsText]);
            } else {
                $message = t('setup_completed_message_success', ['summary' => $summaryText]);
            }
        } catch (Throwable $e) {
            $message = t('setup_completed_message_error', ['message' => $e->getMessage()]);
        }
        render(t('setup_completed_title'), '<section class="card"><h2>' . htmlspecialchars(t('setup_completed_heading')) . '</h2><p>' . htmlspecialchars($message) . '</p><p>' . htmlspecialchars(t('setup_completed_reload')) . '</p></section>');
        exit;
    }
} catch (Throwable $e) {
    render(t('setup_error_title'), '<section class="card alert"><h2>' . htmlspecialchars(t('setup_error_heading')) . '</h2><p>' . htmlspecialchars(t('setup_error_message', ['message' => $e->getMessage()])) . '</p></section>');
    exit;
}

require_once __DIR__ . '/src/migrations.php';
if (schemaMigrationPending()) {
    try {
        runAllPendingMigrations();
    } catch (Throwable $e) {
        render(t('setup_error_title'), '<section class="card alert"><h2>' . htmlspecialchars(t('setup_error_heading')) . '</h2><p>' . htmlspecialchars(t('setup_error_message', ['message' => $e->getMessage()])) . '</p></section>');
        exit;
    }
}

$pdo = getPDO();

require_once __DIR__ . '/src/part_translations_sync.php';
if (partTranslationsSyncPending()) {
    try {
        stepPartTranslationsSync();
    } catch (Throwable $e) {
        // Non-fatal: a translation sync hiccup shouldn't take the whole app
        // down. It'll just retry on the next request.
    }
}

function render(string $title, string $content): void
{
    echo '<!DOCTYPE html><html lang="' . htmlspecialchars(getLocale()) . '"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">';
    echo '<title>' . htmlspecialchars($title) . '</title>';
    echo '<link rel="icon" type="image/svg+xml" href="favicon.svg">';
    echo '<link rel="stylesheet" href="style.css?v=' . htmlspecialchars(getCurrentVersion()) . '">';
    echo '</head><body class="auth-page">';
    echo '<div class="container">';
    echo '<header><div class="brand"><span class="brand-mark">' . file_get_contents(__DIR__ . '/logo.svg') . '</span><div><h1>' . htmlspecialchars(t('app_title')) . '</h1><small>' . htmlspecialchars(t('app_tagline')) . '</small></div></div></header>';
    echo $content;
    echo '<footer>' . htmlspecialchars(t('app_footer', ['year' => date('Y'), 'version' => getCurrentVersion(), 'date' => getVersionDate()])) . '</footer>';
    echo '</div></body></html>';
}

function getNavMenu(PDO $pdo): array
{
    $ownedThemeTree = getOwnedSetThemeTree($pdo);
    $mySetsChildren = buildOwnedThemeNavItems($ownedThemeTree, getSetThemeChildren($ownedThemeTree, null));

    return [
        ['icon' => 'dashboard', 'labelKey' => 'dashboard_title', 'href' => $_SERVER['PHP_SELF'], 'children' => []],
        ['icon' => 'build', 'labelKey' => 'nav_build', 'href' => '?page=build', 'children' => []],
        ['icon' => 'sets', 'labelKey' => 'nav_sets', 'href' => '?page=sets', 'children' => [
            ['labelKey' => 'nav_sets_search', 'href' => '?page=sets_search'],
            ['labelKey' => 'nav_minifigs_search', 'href' => '?page=minifigs_search'],
        ]],
        ['icon' => 'bricks', 'labelKey' => 'nav_bricks', 'href' => '?page=bricks', 'children' => [
            ['labelKey' => 'nav_bricks_search', 'href' => '?page=bricks_search'],
            ['labelKey' => 'nav_colors_search', 'href' => '?page=colors_search'],
        ]],
        ['icon' => 'my_sets', 'labelKey' => 'nav_my_sets', 'href' => '?page=my_sets', 'children' => $mySetsChildren],
        ['icon' => 'my_bricks', 'labelKey' => 'nav_my_bricks', 'href' => '?page=my_bricks', 'children' => [
            ['labelKey' => 'nav_my_bricks_all', 'href' => '?page=my_bricks_all'],
            ['labelKey' => 'nav_my_bricks_by_location', 'href' => '?page=my_bricks_by_location'],
            ['labelKey' => 'nav_my_bricks_by_type', 'href' => '?page=my_bricks_by_type'],
        ]],
        ['icon' => 'locations', 'labelKey' => 'locations_title', 'href' => '?page=locations', 'children' => [
            ['labelKey' => 'nav_locations_tree', 'href' => '?page=locations'],
        ]],
        ['icon' => 'collection', 'labelKey' => 'nav_my_collection', 'href' => '?page=my_collection', 'children' => []],
    ];
}

/**
 * Turns a level of getSetThemeChildren() output into nav-dropdown item
 * shape, recursing into owned subthemes so the "Meine Sets" menu can flyout
 * into them (e.g. Train -> 9V) instead of only showing the top level.
 *
 * @param array<int, array{theme_id:int, name:string, recursive_count:int}> $themeNodes
 * @return array<int, array{label:string, href:string, children?:array}>
 */
function buildOwnedThemeNavItems(array $tree, array $themeNodes): array
{
    $items = [];
    foreach ($themeNodes as $theme) {
        $item = [
            'label' => $theme['name'],
            'href' => '?page=my_sets_themes&theme=' . $theme['theme_id'],
        ];
        $subThemes = getSetThemeChildren($tree, $theme['theme_id']);
        if (!empty($subThemes)) {
            $item['children'] = buildOwnedThemeNavItems($tree, $subThemes);
        }
        $items[] = $item;
    }
    return $items;
}

/**
 * Renders one level of nav-dropdown items, recursing into a ".nav-subdropdown"
 * flyout for any item that carries its own 'children' (see
 * buildOwnedThemeNavItems()). Items may use either 'label' (already a
 * display string, e.g. a theme name) or 'labelKey' (translated).
 *
 * @param array<int, array{label?:string, labelKey?:string, href:string, children?:array}> $items
 */
function renderNavDropdownItems(array $items): string
{
    $html = '';
    foreach ($items as $item) {
        $label = $item['label'] ?? t($item['labelKey']);
        $href = htmlspecialchars($item['href']);
        if (!empty($item['children'])) {
            $html .= '<div class="nav-dropdown-item">';
            $html .= '<a href="' . $href . '">' . htmlspecialchars($label) . '</a>';
            $html .= '<div class="nav-subdropdown">' . renderNavDropdownItems($item['children']) . '</div>';
            $html .= '</div>';
        } else {
            $html .= '<a href="' . $href . '">' . htmlspecialchars($label) . '</a>';
        }
    }
    return $html;
}

function getSearchScopes(): array
{
    return [
        'search' => 'search_scope_all',
        'sets_search' => 'nav_sets',
        'bricks_search' => 'nav_bricks',
        'my_sets_all' => 'nav_my_sets',
        'my_bricks_all' => 'nav_my_bricks',
    ];
}

/**
 * @param array<int, array{label:string, url:?string}> $items Ordered trail,
 *        Dashboard first, current page last (its url must be null — not a
 *        link). Renders nothing for a trail of 0 or 1 items: a lone
 *        "Dashboard" crumb on the dashboard itself isn't worth showing.
 */
function renderBreadcrumbs(array $items): string
{
    if (count($items) < 2) {
        return '';
    }
    $parts = [];
    foreach ($items as $item) {
        $parts[] = $item['url'] !== null
            ? '<a href="' . htmlspecialchars($item['url']) . '">' . htmlspecialchars($item['label']) . '</a>'
            : '<span aria-current="page">' . htmlspecialchars($item['label']) . '</span>';
    }
    return '<nav class="breadcrumbs" aria-label="' . htmlspecialchars(t('breadcrumbs_label')) . '">' . implode('<span class="breadcrumb-sep">»</span>', $parts) . '</nav>';
}

/**
 * The Dashboard crumb every trail starts with.
 */
function homeBreadcrumb(): array
{
    return ['label' => t('dashboard_title'), 'url' => $_SERVER['PHP_SELF']];
}

/**
 * Renders already year-sorted items (each with a ?int 'year' key) as cards
 * grouped under a full-width year heading, inserted whenever the year
 * changes from the previous item — used by sets_search and minifigs_search,
 * both sorted oldest-first then by number. $startYear/$startYearKnown carry
 * the open group across a paginated/AJAX-continued batch (the initial page
 * passes $startYearKnown = false; a continuation passes back the previous
 * batch's returned lastYear/lastYearKnown) so the heading isn't repeated
 * mid-group just because a page boundary happened to fall there.
 *
 * @return array{html: string, lastYear: ?int, lastYearKnown: bool}
 */
function renderYearGroupedCards(array $items, ?int $startYear, bool $startYearKnown, callable $cardRenderer): array
{
    $html = '';
    $currentYear = $startYear;
    $currentYearKnown = $startYearKnown;
    foreach ($items as $item) {
        $year = $item['year'] ?? null;
        if (!$currentYearKnown || $year !== $currentYear) {
            $yearLabel = $year !== null ? (string) $year : t('year_unknown');
            $html .= '<div class="group-header"><span class="group-header-label">' . htmlspecialchars($yearLabel) . '</span><hr class="group-header-rule"></div>';
            $currentYear = $year;
            $currentYearKnown = true;
        }
        $html .= $cardRenderer($item);
    }
    return ['html' => $html, 'lastYear' => $currentYear, 'lastYearKnown' => $currentYearKnown];
}

function renderApp(string $title, string $content, array $user, array $stats, array $breadcrumbs = []): void
{
    $locale = getLocale();
    $currentPage = (string) ($_GET['page'] ?? '');

    echo '<!DOCTYPE html><html lang="' . htmlspecialchars($locale) . '"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">';
    echo '<title>' . htmlspecialchars($title) . '</title>';
    echo '<link rel="icon" type="image/svg+xml" href="favicon.svg">';
    echo '<link rel="stylesheet" href="style.css?v=' . htmlspecialchars(getCurrentVersion()) . '">';
    echo '</head><body>';

    echo '<div class="status-bar-wrap"><div class="status-bar">';
    echo '<div class="status-stats">';
    echo '<span class="status-stat" id="status-stat-bricks_total"><strong>' . number_format($stats['bricks_total']) . '</strong> ' . htmlspecialchars(t('stat_bricks_total')) . '</span>';
    echo '<span class="status-stat" id="status-stat-bricks_distinct"><strong>' . number_format($stats['bricks_distinct']) . '</strong> ' . htmlspecialchars(t('stat_bricks_distinct')) . '</span>';
    echo '<span class="status-stat" id="status-stat-sets"><strong>' . number_format($stats['sets']) . '</strong> ' . htmlspecialchars(t('stat_sets')) . '</span>';
    echo '<span class="status-stat" id="status-stat-minifigs"><strong>' . number_format($stats['minifigs']) . '</strong> ' . htmlspecialchars(t('stat_minifigs')) . '</span>';
    echo '<span class="status-stat" id="status-stat-bricks_damaged"><strong>' . number_format($stats['bricks_damaged']) . '</strong> ' . htmlspecialchars(t('stat_bricks_damaged')) . '</span>';
    echo '</div>';
    echo '<div class="status-user">';
    echo '<a class="status-username" href="?page=settings">' . htmlspecialchars($user['username']) . '</a>';
    echo '<a class="status-icon-link" href="?page=settings" title="' . htmlspecialchars(t('settings_title')) . '">' . getNavIcon('settings') . '</a>';
    echo '<a class="status-icon-link" href="?action=logout" title="' . htmlspecialchars(t('logout')) . '">' . getNavIcon('logout') . '</a>';
    $redirectPage = $currentPage !== '' ? '&page=' . urlencode($currentPage) : '';
    echo '<div class="lang-switcher">';
    echo '<span class="lang-current"><span class="flag-icon">' . getFlagIcon($locale) . '</span></span>';
    echo '<div class="lang-dropdown">';
    foreach (getAvailableLocales() as $flagLocale => $flagLabel) {
        $activeClass = $flagLocale === $locale ? ' active' : '';
        $flagHref = htmlspecialchars('?action=set_locale&locale=' . $flagLocale . $redirectPage);
        echo '<a class="lang-option' . $activeClass . '" href="' . $flagHref . '"><span class="flag-icon">' . getFlagIcon($flagLocale) . '</span>' . htmlspecialchars($flagLabel) . '</a>';
    }
    echo '</div>';
    echo '</div>';
    echo '</div>';
    echo '</div></div>';

    echo '<div class="main-nav-wrap"><header class="main-nav">';
    echo '<a class="logo-link" href="' . htmlspecialchars($_SERVER['PHP_SELF']) . '"><span class="logo-mark">' . file_get_contents(__DIR__ . '/logo.svg') . '</span><span class="logo-text">' . htmlspecialchars(t('app_title')) . '</span></a>';
    echo '<nav class="nav-list">';
    foreach (getNavMenu(getPDO()) as $item) {
        echo '<div class="nav-item">';
        echo '<a class="nav-link" href="' . htmlspecialchars($item['href']) . '"><span class="nav-icon">' . getNavIcon($item['icon']) . '</span><span class="nav-label">' . htmlspecialchars(t($item['labelKey'])) . '</span></a>';
        if (!empty($item['children'])) {
            echo '<div class="nav-dropdown">' . renderNavDropdownItems($item['children']) . '</div>';
        }
        echo '</div>';
    }
    echo '</nav>';
    echo '<form class="nav-search" method="get" action="' . htmlspecialchars($_SERVER['PHP_SELF']) . '">';
    echo '<select name="page" aria-label="' . htmlspecialchars(t('search_scope_label')) . '">';
    foreach (getSearchScopes() as $scopeValue => $scopeLabelKey) {
        echo '<option value="' . htmlspecialchars($scopeValue) . '">' . htmlspecialchars(t($scopeLabelKey)) . '</option>';
    }
    echo '</select>';
    echo '<input type="search" name="q" placeholder="' . htmlspecialchars(t('search_placeholder')) . '" aria-label="' . htmlspecialchars(t('search_placeholder')) . '">';
    echo '<button type="submit">' . htmlspecialchars(t('search_button')) . '</button>';
    echo '</form>';
    echo '</header></div>';

    echo '<div class="container">';
    echo '<main>' . renderBreadcrumbs($breadcrumbs) . $content . '</main>';
    echo '<footer>' . htmlspecialchars(t('app_footer', ['year' => date('Y'), 'version' => getCurrentVersion(), 'date' => getVersionDate()])) . '</footer>';
    echo '</div>';
    echo '</body></html>';
}

/**
 * Only ever a same-app relative path (no scheme/host) — guards the login
 * form's "redirect" field against being used as an open redirect to an
 * off-site URL.
 */
function isSafeLocalRedirectTarget(string $path): bool
{
    return $path !== '' && $path[0] === '/' && !str_starts_with($path, '//') && !str_contains($path, '://');
}

if (isset($_POST['action']) && $_POST['action'] === 'login') {
    $username = trim($_POST['username'] ?? '');
    $password = $_POST['password'] ?? '';
    $loginRedirect = (string) ($_POST['redirect'] ?? '');
    $loginRedirectTarget = isSafeLocalRedirectTarget($loginRedirect) ? $loginRedirect : $_SERVER['PHP_SELF'];
    $stmt = $pdo->prepare('SELECT id, password_hash FROM users WHERE username = ?');
    $stmt->execute([$username]);
    $user = $stmt->fetch();
    if ($user && password_verify($password, $user['password_hash'])) {
        $_SESSION['user_id'] = $user['id'];
        header('Location: ' . $loginRedirectTarget);
        exit;
    }
    render(t('login_failed_title'), '<section class="card alert"><h2>' . htmlspecialchars(t('login_failed_heading')) . '</h2><p>' . htmlspecialchars(t('login_failed_message')) . '</p></section>');
    exit;
}

require_once __DIR__ . '/src/routes/pre_auth.php';

if (!isset($_SESSION['user_id'])) {
    $loginRedirectField = isSafeLocalRedirectTarget((string) ($_SERVER['REQUEST_URI'] ?? '')) ? $_SERVER['REQUEST_URI'] : '';
    $content = '<section class="card"><h2>' . htmlspecialchars(t('login_title')) . '</h2><form method="post"><input type="hidden" name="action" value="login"><input type="hidden" name="redirect" value="' . htmlspecialchars($loginRedirectField) . '"><label>' . htmlspecialchars(t('login_username')) . '<input name="username" autocomplete="username"></label><label>' . htmlspecialchars(t('login_password')) . '<input type="password" name="password" autocomplete="current-password"></label><button type="submit">' . htmlspecialchars(t('login_button')) . '</button></form></section>';
    render(t('login_title'), $content);
    exit;
}

require_once __DIR__ . '/src/routes/actions.php';

$stmt = $pdo->prepare('SELECT id, username, full_name, is_admin FROM users WHERE id = ?');
$stmt->execute([$_SESSION['user_id']]);
$user = $stmt->fetch();

if ($user === false) {
    session_destroy();
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
}
$user['is_admin'] = (bool) $user['is_admin'];

$adminUserMessage = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'admin_create_user') {
    // Re-checked here, not just hidden in the UI — self-registration is
    // gone specifically so that creating an account is an admin-only
    // action, and a non-admin could otherwise still POST this directly.
    if (!$user['is_admin']) {
        http_response_code(403);
        exit;
    }
    $newFullName = trim((string) ($_POST['full_name'] ?? ''));
    $newUsername = trim((string) ($_POST['username'] ?? ''));
    $newPassword = (string) ($_POST['password'] ?? '');
    $newPasswordConfirm = (string) ($_POST['password_confirm'] ?? '');
    $newEmail = trim((string) ($_POST['email'] ?? ''));
    $newIsAdmin = ($_POST['is_admin'] ?? '') === '1';

    if ($newFullName === '' || $newUsername === '' || $newPassword === '') {
        $adminUserMessage = t('admin_user_required');
    } elseif ($newPassword !== $newPasswordConfirm) {
        $adminUserMessage = t('admin_user_password_mismatch');
    } else {
        try {
            $existsStmt = $pdo->prepare('SELECT id FROM users WHERE username = ?');
            $existsStmt->execute([$newUsername]);
            if ($existsStmt->fetchColumn() !== false) {
                throw new RuntimeException(t('admin_user_exists'));
            }
            $hash = password_hash($newPassword, PASSWORD_DEFAULT);
            $insertStmt = $pdo->prepare('INSERT INTO users (username, password_hash, email, full_name, is_admin) VALUES (?, ?, ?, ?, ?)');
            $insertStmt->execute([$newUsername, $hash, $newEmail !== '' ? $newEmail : null, $newFullName, $newIsAdmin ? 1 : 0]);
            $adminUserMessage = t('admin_user_created', ['username' => $newUsername]);
        } catch (Throwable $e) {
            $adminUserMessage = t('admin_user_save_failed', ['message' => $e->getMessage()]);
        }
    }
}

require_once __DIR__ . '/src/routes/pages.php';

$stubPages = [
    'search' => 'search_scope_all',
    'build' => 'nav_build',
    'sets' => 'nav_sets',
    'bricks' => 'nav_bricks',
    'colors_search' => 'nav_colors_search',
    'my_bricks' => 'nav_my_bricks',
    'my_bricks_all' => 'nav_my_bricks_all',
    'my_bricks_by_location' => 'nav_my_bricks_by_location',
    'my_bricks_by_type' => 'nav_my_bricks_by_type',
    'my_collection' => 'nav_my_collection',
];
$requestedPage = (string) ($_GET['page'] ?? '');
if ($requestedPage !== '' && isset($stubPages[$requestedPage])) {
    $stubTitle = t($stubPages[$requestedPage]);
    $searchQuery = trim((string) ($_GET['q'] ?? ''));
    $content = '<h1>' . htmlspecialchars($stubTitle) . '</h1>';
    if ($searchQuery !== '') {
        $content .= '<p>' . htmlspecialchars(t('search_results_for', ['query' => $searchQuery])) . '</p>';
    }
    $content .= '<section class="card"><p>' . htmlspecialchars(t('feature_not_implemented')) . '</p></section>';
    renderApp($stubTitle, $content, $user, computeAppStats($pdo), [homeBreadcrumb(), ['label' => $stubTitle, 'url' => null]]);
    exit;
}

$dashboardCollectionName = getAppSetting('collection_name', t('app_title'));
$dashboardDisplayName = $user['full_name'] !== null && $user['full_name'] !== '' ? $user['full_name'] : $user['username'];
$content = '<h1>' . htmlspecialchars(t('dashboard_welcome_message', ['collection' => $dashboardCollectionName, 'name' => $dashboardDisplayName])) . '</h1>';
if ($importMessage !== '') {
    $content .= '<p><strong>' . htmlspecialchars($importMessage) . '</strong></p>';
}
$content .= renderDashboardWidgets($pdo, (int) $user['id']);
renderApp(t('dashboard_title'), $content, $user, computeAppStats($pdo));
